### ISSUE TITLE
[API. Tasks] User is not able to create a task with allowed special characters in 'name' field

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#1000]
**Environment**: Windows 10 x64, Postman v9.0.7.
**Reproducible**: always.
**Build found**: last commit.

**Preconditions:**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Enter request URL: https://speak-ukrainian.org.ua/dev/api/challenge/1/task
4. Navigate to 'Authorization' tab, choose 'Bearer Token' in 'Type' drop-down
5. Set 'accessToken' of user with admin rights (e. g. 'email': "admin@gmail.com", 'password': "admin") in 'Token' field

**Steps to reproduce:**
1. Choose Body > raw > JSON
2. Enter a request to create new task with special characters that allowed, according to validation:
{
    "name": "\\&*#$%&'*+)*-.:,<=>",
    "headerText": "\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>",
    "description": "\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>\\&*#$%&'*+)*-.:,<=>",
    "picture": "/upload/test/test.png",
    "startDate": "5000-10-28"
}
3. Click on 'Send' button.

**Actual result**
Server is respond with 400 status - 'Internal Server Error' and 'name can contains only letters of ukrainian and english languages, numbers, and some special symbols like: [\"#$%&'*+ ,-.:;<=>?|@_`{}~]' error.

**Expected result**
Server should respond with status 200 and task should be created without any errors.

<details>
  <summary>Screenshot:</summary>

![Screenshot_124](https://user-images.githubusercontent.com/79206807/139195325-8f093f7d-fd19-46a2-ae04-54f879c331e3.png)
</details>

**Comment by Wollene** [comment]
Not fixed, problem is still exist.

<details>
<summary>Screenshot:</summary>

![Screenshot_129](https://user-images.githubusercontent.com/79206807/139525969-9b5a206b-9dce-48c3-965a-ccc539960d17.png)
</details>

**Comment by Wollene** [comment]
**ADDITION**
Problem is also exist for Challenges - 'title' field.

<details>
<summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/79206807/139541497-9fd19e64-1ccb-4346-9634-656076674def.png)
</details>

**Comment by AnastasiiaKukh** [comment]
The same error exists, when we edit Task, but enter special characters in the headerText .

![изображение_2021-11-03_155011](https://user-images.githubusercontent.com/89512453/140072387-aeec6642-81a4-4872-ad64-e35b009df37c.png)

**Comment by RomanKlymus** [comment]
> 
> 
> Not fixed, the problem is still exist.
> Screenshot:
> 
> ![Screenshot_129](https://user-images.githubusercontent.com/79206807/139525969-9b5a206b-9dce-48c3-965a-ccc539960d17.png)
Not a bug. Html validator <=> recognizes as a tag.

**Comment by RomanKlymus** [comment]
> The same error exists, when we edit Task, but enter special characters in the headerText .
> 
> ![изображение_2021-11-03_155011](https://user-images.githubusercontent.com/89512453/140072387-aeec6642-81a4-4872-ad64-e35b009df37c.png)


Not a bug. Somewhere in JSON is not correct character escape.

**Comment by AnastasiiaKukh** [comment]
Bug is fixed and close
