### ISSUE TITLE
[Мій профіль] User cannot delete centers from 'Мій профіль' page

### ISSUE THREAD

**Issue by RomanSahan** [ita-social-projects/TeachUA#1007]
**Environment:** Windows 10, Google Chrome, 93.0.4577.63 (Розробка) (64-розрядна версія)
**Reproducible:** rarely
**Build found:** the last commit 

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Login with any account, which has registered at least one center (e.g. емейл: roman2002sahan@gmail.com, пароль: wiwko1234567_)

**Steps to reproduce**
1. Select 'Мій профіль' in the dropdown list on the upper left corner of the page
2. Click on 'Видалити' in the burger menu of the center

**Actual result**
The page is reloaded. The center is not deleted
**Expected result**
The page is reloaded. The center is deleted. Message about the successful deletion of the center appears

https://user-images.githubusercontent.com/80393478/139246920-ff3ee03a-a593-4f77-9a0e-bb8abefac0d2.mp4

**Comment by roman-rd15** [comment]
User with "ROLE_USER" permissions cannot add or remove centers

**Comment by RomanSahan** [comment]
The bug is fixed
