### ISSUE TITLE
[API. Feedback] Missing validation of fields on backend when user tries send empty values in request through API

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#1043]
**Environment**: Windows 10 x64, Postman v9.0.7.
**Reproducible**: always.
**Build found**: last commit.

**Preconditions:**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Enter request URL: https://speak-ukrainian.org.ua/dev/api/feedback
4. Navigate to 'Authorization' tab, choose 'Bearer Token' in 'Type' drop-down
5. Set 'accessToken' of any user (e. g. 'email': "admin@gmail.com", 'password': "admin") in 'Token' field

**Steps to reproduce**
1. Choose Body > raw > JSON
2. Enter a request to create feedback with empty values:
`{
    "text": "",
    "rate": "",
    "userId": "",
    "userName": "",
    "clubId": ""
}`
3. Enter a request to create feedback with null values:
`{
    "text": null,
    "rate": null,
    "userId": null,
    "userName": null,
    "clubId": null
}`
4. Enter a request to create feedback with spaces:
`{
    "text": "    ",
    "rate": "    ",
    "userId": "    ",
    "userName": "    ",
    "clubId": "    "
}`

**Actual result**
In all cases server is responding with 500 status - 'Internal Server Error' and no any error messages appear.

**Expected result**
In all cases server should respond with status 400 and propper error messages should be displayed.

**User story and test case links**
Validation of the fields should be performed according user stories below:
- #115 
- #287 

<details>
<summary>Screenshots:</summary>

Actual result - **null** value
![Screenshot_145](https://user-images.githubusercontent.com/79206807/140021218-ab2f6fee-d274-44dd-87db-7ff2eeaaed70.png)

Actual result - **spaces**
![Screenshot_146](https://user-images.githubusercontent.com/79206807/140021285-d2ecd24e-abbe-47c4-9e8c-f3aa6efe3c91.png)

Actual result - **empty** value
![Screenshot_147](https://user-images.githubusercontent.com/79206807/140021323-3de367f2-0fe8-4f13-b1f5-c5659fc79986.png)
</details>

**Comment by AnastasiiaKukh** [comment]
Bug is fixed and close
