### ISSUE TITLE
[API. Feedback & Complaint] Missing validation on existing user in 'userId' field and existing club in 'clubId' field

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#1044]
**Environment**: Windows 10 x64, Postman v9.0.7.
**Reproducible**: always.
**Build found**: last commit.

**Preconditions:**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Navigate to 'Authorization' tab, choose 'Bearer Token' in 'Type' drop-down
4. Set 'accessToken' of any user (e. g. 'email': "admin@gmail.com", 'password': "admin") in 'Token' field

**Steps to reproduce**
1. Choose Body > raw > JSON
2. Enter request URL: https://speak-ukrainian.org.ua/dev/api/feedback
3. Enter a request to create **feedback** with non-existing 'userId' (e. g. '234341111111111') and 'clubId' (e. g. '434222222222223') values:
`{
    "text": "Some text",
    "rate": 2,
    "userId": "234341111111111",
    "userName": "Some User",
    "clubId": "434222222222223"
}`
4. Enter request URL: https://speak-ukrainian.org.ua/dev/api/complaint
5. Enter a request to create **complaint** with non-existing 'userId' (e. g. '234341111111111') and 'clubId' (e. g. '434222222222223') values:
`{
    "text": "Some text Some text Some text Some text",
    "userId": "234341111111111",
    "date": "2021-11-03",
    "clubId": "434222222222223"
}`

**Actual result**
In all cases server is responding with 500 status - 'Internal Server Error' and no any error messages appear.

**Expected result**
In all cases server should respond with status 400, system should check if entered user or club is exist and if it is not - propper error messages should be displayed.

**User story and test case links**
Validation of the fields should be performed according user stories below:
- #115 
- #287 

<details>
<summary>Screenshots:</summary>

Actual result - **feedback**
![Screenshot_148](https://user-images.githubusercontent.com/79206807/140023434-c74c1297-fb17-4d26-8ee0-8b6f42c5b72d.png)

Actual result - **complaint**
![Screenshot_149](https://user-images.githubusercontent.com/79206807/140023483-8840fa6c-cc84-4d77-ba10-4b00ac5df519.png)
</details>

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
