### ISSUE TITLE
[API. Complaint] User can add incorrect (past or future) date when sending complaint through API

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#1045]
**Environment**: Windows 10 x64, Postman v9.0.7.
**Reproducible**: always.
**Build found**: last commit.

**Preconditions:**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Enter request URL: https://speak-ukrainian.org.ua/dev/api/complaint
4. Navigate to 'Authorization' tab, choose 'Bearer Token' in 'Type' drop-down
5. Set 'accessToken' of any user (e. g. 'email': "admin@gmail.com", 'password': "admin") in 'Token' field

**Steps to reproduce**
1. Choose Body > raw > JSON
2. Enter a request to create **complaint** with 'date' value (e. g. '0000-01-01' or '9999-12-31'):
`{
    "text": "Some text Some text Some text Some text",
    "userId": "1",
    "date": "0000-01-01",
    "clubId": "903"
}`
OR
`{
    "text": "Some text Some text Some text Some text",
    "userId": "1",
    "date": "9999-12-31",
    "clubId": "903"
}`

**Actual result**
In all cases server is responding with 200 status - 'OK'.

**Expected result**
In all cases server should respond with status 400, system should check if entered date and if it is past or future date - proper error messages should be displayed.

**User story and test case links**
Validation of the fields should be performed according user stories below:
- #115 
- #287 

<details>
<summary>Screenshots:</summary>

Actual result - **"date": "0000-01-01**
![Screenshot_150](https://user-images.githubusercontent.com/79206807/140027871-be5d9c8e-2850-4cac-ab8f-a1085fc3b92e.png)

Actual result - **"date": "9999-12-31"**
![Screenshot_151](https://user-images.githubusercontent.com/79206807/140027886-15a82609-4143-440e-869f-5f06d64822cf.png)
</details>

**Comment by AnastasiiaKukh** [comment]
Bug is repruduc
![изображение_2021-11-15_143154](https://user-images.githubusercontent.com/89512453/141782754-56f1afba-7cdd-4463-8861-e61ebef91b32.png)

**Comment by Olha-Pylyp** [comment]
Bug is fixed
