### ISSUE TITLE
[API. Feedback & Complaint] User can write feedback and complaints using 'userId' of another user

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#1048]
**Environment**: Windows 10 x64, Postman v9.0.7.
**Reproducible**: always.
**Build found**: last commit.

**Preconditions:**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Navigate to 'Authorization' tab, choose 'Bearer Token' in 'Type' drop-down
4. Set 'accessToken' of any user (see **Test data** item) in 'Token' field

**Test data**
1. Administrator user - **email**: "admin@gmail.com", **password**: "admin" - **id**: 1
2. Non-administrator user - **email**: "ulpkzrapmhkpzaqcve@sdvgeft.com", **password**: "11111111" - **id**: 259

**Steps to reproduce**
1. Choose Body > raw > JSON
2. Enter request URL: https://speak-ukrainian.org.ua/dev/api/feedback
3. Enter a request to create **feedback** autorised as administrator (**id**: 1) using different id (**id**: 260):
`{
    "text": "Sample Text Sample Text Sample",
    "rate": 2,
    "userId": 260,
    "userName": "Some User",
    "clubId": 27
}`
4. Enter a request to create **feedback** autorised as non-administrator (**id**: 259) using different id (**id**: 260):
`{
    "text": "Sample Text Sample Text Sample",
    "rate": 2,
    "userId": 260,
    "userName": "Some User",
    "clubId": 27
}`
5. Enter request URL: https://speak-ukrainian.org.ua/dev/api/complaint
6. Enter a request to create **complaint** autorised as administrator (**id**: 1) using different id (**id**: 260):
`{
    "text": "Sample Text Sample Text Sample",
    "userId": 260,
    "date": "2021-11-03",
    "clubId": 27
}`
7. Enter a request to create **complaint** autorised as non-administrator (**id**: 259) using different id (**id**: 260):
`{
    "text": "Sample Text Sample Text Sample",
    "userId": 260,
    "date": "2021-11-03",
    "clubId": 27
}`

**Actual result**
Any user with any rights can write feedbacks and complaints from the name of another user using their 'userId'. Server responds with status code 200 and feedback/complaint successfully created.

**Expected result**
User shouldn't be able to create feedbacks and complaints from the name of another user. User should be authorized and use only his/her 'userId' to write feedback/complaint. 
- If user tries to write feedback/complaint using 'userId' of another user, server should respond with code 401 and proper error message should be displayed.
- If user tries to write feedback/complaint using his/her own 'userId's erver should respond with code 200 and feedback/complaint should be created without any error messages.

**User story and test case links**
Validation of the fields should be performed according user stories below:
- #115 
- #287 

<details>
<summary>Screenshots:</summary>

Actual result - **feedback**
![Screenshot_156](https://user-images.githubusercontent.com/79206807/140040582-5b57d3c3-bc97-4591-b636-a63ca1ce4916.png)

Actual result - **complaint**
![Screenshot_155](https://user-images.githubusercontent.com/79206807/140040499-88d37297-9d2d-4ee2-b3e4-927054c007d4.png)
</details>

**Comment by Olha-Pylyp** [comment]
Bug is fixed.
