### ISSUE TITLE
[API. Додати гурток] User can create a club by changing his ID to another user's ID 

### ISSUE THREAD

**Issue by AnastasiiaKukh** [ita-social-projects/TeachUA#1061]
**Environment**: Postman v9.0.3
**Reproducible**: Always
**Build found**: Last commit

**Preconditions**

1. Run Postman
2. Sign in via Postman as a User (e.g : Url - https://speak-ukrainian.org.ua/dev/api/signin, Method - 'Post', body: {
  "email": "soyec48727@busantei.com",
  "password": "12345678"
}  )
![изображение_2021-11-05_111946](https://user-images.githubusercontent.com/89512453/140487686-566a6e23-4990-49d7-bf34-200e3d1577cc.png)
3. Use the token of the user from id 203

**Steps to reproduce**

1. Select the method POST in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/club
3. Click on the Body tab and select Raw-> (change userId)

{"categoriesName":["Танці, хореографія","Студії раннього розвитку"],
"name":"Test123456789",
"ageFrom":4,
"ageTo":6,
"description":"{\"blocks\":[{\"key\":\"brl63\",\"text\":\"TestNastiaTestNastiaTestNastiaTestNastiaTestNastia\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
**"userId": "237"**,
"locations":[{"name":"Nastia Kukharska",
"cityName":"Львів",
"address":"Vernadskoho,14",
"coordinates":"49.84390002605753, 24.023461667439843","phone":"123456789","key":0.5695778324541552}],
"contacts":"{\"1\"::\"123456789\"}"}

**Actual result**
Club is create successfully.
![изображение_2021-11-05_112413](https://user-images.githubusercontent.com/89512453/140488319-dfee2c1c-72f0-4e12-bceb-1df062634a94.png)

**Expected result**
We can not change "userId". An appear error message

"User story #70

**Comment by AnastasiiaKukh** [comment]
Bug is reproduce.

**Comment by OH72** [comment]
No matter what id is inputted in "user Id" field, if user creates club, it automatically assigned to the user which created club.
("user Id" field is ignored during creating club)
![зображення](https://user-images.githubusercontent.com/79600913/141682039-b9d2632e-3f02-43f7-a4ce-ffd331c6aa85.png)
![зображення](https://user-images.githubusercontent.com/79600913/141682092-db13a801-6dd1-4dda-997c-e3a143302df9.png)

**Comment by AnastasiiaKukh** [comment]
Bug is fixed and close
