### ISSUE TITLE
[API. Додати гурток] An appear 500 error where user try to create a club.

### ISSUE THREAD

**Issue by AnastasiiaKukh** [ita-social-projects/TeachUA#1095]
**Environment**: Postman v9.0.3
**Reproducible**: Always
**Build found**: Last commit

**Preconditions**

1. Run Postman
2. Sign in via Postman as a User (e.g : Url - https://speak-ukrainian.org.ua/dev/api/signin, Method - 'Post', body: {
"email": "soyec48727@busantei.com",
"password": "12345678"
} )

**Steps to reproduce**

1. Select the method POST in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/club
3. Click on the Body tab and select Raw-> 

{"categoriesName":["Танці, хореографія","Студії раннього розвитку"],
"name":"Test123456789121221",
"ageFrom":4,
"ageTo":6,
"description":"{\"blocks\":[{\"key\":\"brl63\",\"text\":\"TestNastiaTestNastiaTestNastiaTestNastiaTestNastia\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
"userId":"203",
"locations":[{"name":"Nastia Kukharska",
"cityName":"Львів",
"address":"Vernadskoho,14",
"coordinates":"49.84390002605753, 24.023461667439843","phone":"123456789","key":0.5695778324541552}],
"contacts":"{\"1\"::\"123456789\"}"}

**Actual result**
An appear 500 error
![изображение_2021-11-10_105422](https://user-images.githubusercontent.com/89512453/141081431-3495b5d7-e7e3-4818-8afe-6c1fdd233333.png)

**Expected result**

"User story #70

**Comment by AnastasiiaKukh** [comment]
The same problem with "Create a center".
![изображение_2021-11-11_091256](https://user-images.githubusercontent.com/89512453/141254346-163aed45-7d88-4d7d-8772-bc0369fde6d0.png)

**Comment by OlenaHevak** [comment]
Not fixed.
![Image 2](https://user-images.githubusercontent.com/91247890/143415660-81d2ff96-920c-46d5-857b-64fdcd3b0fb1.png)
