### ISSUE TITLE
[Додати гурток] new club doesn't displayed on "Мiй профiль" after creating.

### ISSUE THREAD

**Issue by OlenaHevak** [ita-social-projects/TeachUA#1176]
Environment: Windows, Версія 94.0.4606.81 (Розробка) (64-розрядна версія).
Reproducible: always
Build found: https://speak-ukrainian.org.ua/dev

Preconditions:
Log in as "Керівник":
Email - TestTeach.ua@meta.ua
Password: 12345678

Steps to reproduce
1. Go to https://speak-ukrainian.org.ua/dev
2. Click on 'Додати гурток'.
3. Filled all mandatory fields on "Основна iнформацiя ", "Контакти", "Опис" tabs.
4. Click "Завершити" button.
5. Go to the "Мiй профiль".
6. Check if a new club present on the website.

Actual result
New club doesn't present on the website.

Expected result
New club should be present on the website.

E.g.: "User story https://github.com/ita-social-projects/TeachUA/issues/70

"Bug", Priority (High), Severity (Major), Type ("Functional").

**Comment by KostiantynStarynets** [comment]
The actual result coincides with the expected one. Everything works according to the requirements of the test case.

![Знімок екрана 2023-01-17 154054](https://user-images.githubusercontent.com/117648097/212914282-92850abd-53bd-423b-ac64-ed76ac309ec9.jpg)
