### ISSUE TITLE
[Забули пароль?] func changing password, when i enter correct email.

### ISSUE THREAD

**Issue by ShisenSni** [ita-social-projects/TeachUA#1276]
**Environment:** Windows OS, Opera GX browser, 80.0.4170.91 (November 04, 2021)
**Reproducible:** always
**Build found:**  https://speak-ukrainian.org.ua/dev

**Preconditions**
After try to login on my account and i had error **[Неправильно введений логін або пароль]**
I want to change my password for account. 

**Steps to reproduce**
1. Go to link  [ https://speak-ukrainian.org.ua/dev](url)
2. Click on [Увійти]
3. Click on [Забули пароль?]
4. Enter correctly my email.
5. Click on [Відновити]

**Actual result**
I had an error [Користувач з вказаним емейлом не знайдений]
![зображення_2021-12-23_135907](https://user-images.githubusercontent.com/96551212/147237457-032c48bb-b5d7-4473-8df0-e61e512b61e7.png)

**Expected result**
Open a functional of changing password.

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by OH72** [comment]
This bug appeared because of previous bug with registration. Now it must work fine.
