### ISSUE TITLE
[Google Authorization] button on [Вхід] login form doesn't login to the web site 

### ISSUE THREAD

**Issue by NastiaYonka** [ita-social-projects/TeachUA#1278]
**Environment:** Windows 10, Google Chrome, Version 96.0.4664.110 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev /

**Preconditions**
Open https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on the Account button in the top right corner
3. Click on the [Увійти]
4. Click on the Google icon in the center of the Login Form. 
5. Choose your Google account

**Actual result**
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
There was an unexpected error (type=Internal Server Error, status=500).

**Expected result**
Login via Google Account 

**Postconditions**
Reload to get back to the main page.

**Comment by ShisenSni** [comment]
![FECF9528-9C3C-4F39-AE1F-DAD9702A4785](https://user-images.githubusercontent.com/96551212/147735723-b1b9c8a1-8bee-4f1b-bfaa-d8f2376cf6a9.jpeg)

Bug not fixed.
