### ISSUE TITLE
[Редагування профілю] user can't save new information

### ISSUE THREAD

**Issue by ShisenSni** [ita-social-projects/TeachUA#1288]
**Environment:** MacOS 12.1, Safari Версія 15.2 (17612.3.6.1.6), Windows 10, Opera GX, 80.0.4170.91 (November 04, 2021)
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev/

**Preconditions**
User needs to change information.
such as avatar, name, phone number, or pass.
**Steps to reproduce**
### **1 scenario**
1. Go to [https://speak-ukrainian.org.ua/dev/](url)
2. Click on the drop menu "icon of my account"
3. Choose [Мій профіль] 
4. Click on [Редагувати профіль]
5. Make changes in the text fields
6. Click on [Зберегти зміни]
### **2 scenario**
5. Make changes in the text fields **and add a photo.**
6.  Click on [Зберегти зміни]
![telegram-cloud-photo-size-2-5361580393867884282-y](https://user-images.githubusercontent.com/96551212/147661090-3826c7c3-5a98-45f0-b103-89db82ed1ebb.jpg)

### **Actual result**
The first scenario - button [Зберегти зміни] doesn't work.
Second scenario - button [Зберегти зміни] work's we see the message that information save.
![telegram-cloud-photo-size-2-5361580393867884286-y](https://user-images.githubusercontent.com/96551212/147661176-1c394219-02e4-4ed7-83e6-d2b153738355.jpg)

### **Expected result**
Button [Зберегти зміни] works.
User saves that information. 

**Labels to be added**
"Bug", "pri:H", "severity:C", Type "UI"

**Comment by sofiyamarusyk** [comment]
If a user makes some changes in [Редагувати профіль] but he **doesn`t add a photo** and clicks on [Зберегти зміни], **nothing happens**, button [Зберегти зміни] doesn't work. If a user makes some changes and **adds a photo** when he edits his account and clicks on [Зберегти зміни] everything is okay and **information is saved**.
