### ISSUE TITLE
List [Оберіть гурток] in the window [Додати центр] is not displayed 

### ISSUE THREAD

**Issue by NastiaYonka** [ita-social-projects/TeachUA#1296]
**Environment:**  Windows 10, Google Chrome, Version 96.0.4664.110 (Official Build) (64-bit)
**Reproducible:** always 
**Build found:** https://speak-ukrainian.org.ua/dev/

**Preconditions**
 Open https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Log in with an already registered user
2. Click on the Account button in the top right corner 
3. Click on the [Додати центр]
4. Fill in all the mandatory fields of the [Основна інформація] tab
5. Click the [Додати локацію] button
6. In 'Додати локацію' window fill in all fields -> Click [Додати] button
7. Select the location you just created ->click [Наступний крок] button
8. Fill in all the mandatory fields of the [Контакти] tab -> click [Наступний крок] button
9. Fill in all the mandatory fields of the [Опис] tab -> click [Наступний крок] button

**Actual result**
The list of the Гуртки doesn't display 
![image](https://user-images.githubusercontent.com/96540492/148128983-c3f46db7-8ced-4952-866f-b7de65ae6484.png)

**Expected result**
The list of the Гуртки displays 

**Postconditions**
Press x on the top right corner of the window [Додати гурток] to close it.

**Comment by OH72** [comment]
Can you give exact steps or video to reproduce this bug? Because I cant get this bug.

**Comment by NastiaYonka** [comment]
you need first ГУРТКИ to add and than create ЦЕНТР. Not a bug
