### ISSUE TITLE
Fix image gallery in club info

### ISSUE THREAD

**Issue by lyzunyktaras** [ita-social-projects/TeachUA#1322]
Fix image gallery in club information. Delete the hard code of the images and add the images included in the club

**Comment by softservedata** [comment]
do not show slider if images not found

![image](https://user-images.githubusercontent.com/12804385/217774963-315eb2e5-4b29-41a0-b76e-1853ab7cd428.png)

**Comment by Vekeryk** [comment]
Is fixed now
![image](https://user-images.githubusercontent.com/77672827/220878692-447e4dd6-ee9b-47a4-b077-acf78158002d.png)

**Comment by KostiantynStarynets** [comment]
![2Без імені](https://user-images.githubusercontent.com/117648097/221427890-889fe03d-caed-45e3-9fa7-348b63cb3d0d.jpg)
![3Без імені](https://user-images.githubusercontent.com/117648097/221427892-73bb74c1-a28a-4a81-820e-d5a1b3ea8b27.jpg)
![4Без імені](https://user-images.githubusercontent.com/117648097/221427893-6fe77430-7b29-49a6-94e2-c1762bfe42d8.jpg)
![Без імені](https://user-images.githubusercontent.com/117648097/221427951-84923fef-1f3a-461b-addb-8f84b38695dc.jpg)

**Comment by KostiantynStarynets** [comment]
After accepting  "pull request" of the Product, everything works as required.
![22Без імені](https://user-images.githubusercontent.com/117648097/222171809-a6730c25-13b0-42c8-852e-8877aada8692.jpg)
