### ISSUE TITLE
[Завдання] The date is displayed in format yyyy-mm-dd on 'Завдання' page

### ISSUE THREAD

**Issue by NazariiBilohras** [ita-social-projects/TeachUA#1342]
**Environment:** Windows 10 Enterprise, version 20H2, OS build 19042.1586, 
Google Chrome Version 99.0.4844.84 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit
**Preconditions**

1. Log in as an administrator on https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**

1. Click on the drop-down menu (In the upper right corner)
2. Click on the "Адміністрування" menu item and select the 'Завдання' menu item
3. Pay attention to the date format 

**Actual result**
The date is displayed in format yyyy-mm-dd

![Screenshot_1](https://user-images.githubusercontent.com/101584182/160385539-160d0d61-c462-4e5b-b039-8239e8bdc7dc.png)

**Expected result**
The date is displayed in format dd-mm-yyyy.

**User story and test cases**

User story #1335

**Comment by bakaydmytro** [comment]
@NazariiBilohras , can you clarify if its ok when date of task in list are different in edit task page

**Comment by bakaydmytro** [comment]
@NazariiBilohras , also in scope of this fix I will change date format in edit task page and edit challenge page to dd-mm-yyyy

**Comment by dtyta** [comment]
Tested.
