### ISSUE TITLE
[Челендж] Using Invalid language in "Челендж" creating

### ISSUE THREAD

**Issue by IvanKuzmuk** [ita-social-projects/TeachUA#1348]
Environment: Windows 10 Pro 21H1,OS build19043.1586, Google Chrome, version 99.0.4844.84.
Reproducible: always.
Build found:last commit
Preconditions
Log in as an administrator on https://speak-ukrainian.org.ua/dev/
Steps to reproduce"

1. Click on 'Aдміністрування'
2. Click on 'Додати Челендж'
3. Fill in all required fields
4. Fill in with languages which are not required according to the US
5. Created challegne with Japanesse and German languages 
6. Click on "Зберегти" button
**Actual result**
Challenge will be saved

**Expected result**
Challegne would'nt save

https://user-images.githubusercontent.com/57858834/162674623-d0600448-97c6-44ae-b256-928432782563.mp4

https://user-images.githubusercontent.com/57858834/162674643-d07f6e1b-6c9f-45cb-936f-b952224c3580.mp4

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by bakaydmytro** [comment]
@IvanKuzmuk, it would be great if you attached example of expected text with all possible symbols

**Comment by IvanKuzmuk** [comment]
@bakaydmytro According to User Page 1334, it was stated that only English and Ukrainian characters could be used to create a challenge. And what do mean exactly, when you are talking about  text with all possible symbols?

**Comment by bakaydmytro** [comment]
@IvanKuzmuk ,e.g. !@#$%^&*()_+{}<>?/"'`|\

**Comment by dtyta** [comment]
Tested. Fields accept characters in Ukrainian and English language, numbers, with symbols.
