### ISSUE TITLE
[Завдання] After clicking 'Зберегти' button does not redirect to the 'Завдання' page

### ISSUE THREAD

**Issue by NazariiBilohras** [ita-social-projects/TeachUA#1350]
**Environment:** Windows 10 Enterprise, version 20H2, OS build 19042.1586, Google Chrome Version 100.0.4896.75 (Official Build) (64-bit)
**Reproducible:** always,
**Build found:** last commit

**Preconditions**

1. Log in as an administrator on https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**

1. Click on the drop-down menu (In the upper right corner)
2. Click on the 'Адміністрування' menu item and select the 'Завдання' menu item...'
3. Click on 'Додати завдання' 
4. Fill in all required fields
5.  Click on 'Зберегти' button

**Actual result**
After clicking 'Зберегти' button does not redirect to the 'Завдання' page

https://user-images.githubusercontent.com/101584182/162902084-0df32774-c15c-458a-ac2c-3f8a244c11ad.mp4

**Expected result**
All information about the task is saved, and open the 'Завдання' page.

**User story and test case links**
E.g.: "User story #1335

**Comment by dtyta** [comment]
Tested. All information about the task is saved, and open the 'Завдання' page.
