### ISSUE TITLE
[Челендж] Ability to create challenges with the same serial numbers

### ISSUE THREAD

**Issue by IvanKuzmuk** [ita-social-projects/TeachUA#1363]
**Environment:**Windows 10 Pro 21H1,OS build19043.1586, Google Chrome, version 99.0.4844.84
**Reproducible:** always
**Build found:** last commit 

Log in as an administrator on https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Click on the drop-down menu (In the upper right corner)
2. Click on the 'Адміністрування' menu item and select the 'Челендж' menu item
3. Click on "Додати челендж"
4. Fill in all mandatory fields
5. Fill in "Порядковий номер" field with the same value as privious challange
6. Click on "Зберегти" button

**Actual result**
Challagne will be save,two challenges with the same serial numbers will appear

**Expected result**
A pop-up message will appears, which will inform us that challegne with such serial number is already exist, and you can't create it
![ss](https://user-images.githubusercontent.com/57858834/163764406-47f52fe5-fa2e-4414-a7cc-f637b5e15524.PNG)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by KostiantynStarynets** [comment]
![Знімок екрана 2023-01-03 003748](https://user-images.githubusercontent.com/117648097/210451696-69c3abf1-2ee1-4967-a275-cac2743f34ca.jpg)
![Знімок екрана 2023-01-03 003908](https://user-images.githubusercontent.com/117648097/210451701-2c591620-618a-4cf3-bf1d-faa51f2683df.jpg)
According to the requirements of the test, "Челенджі" with the same "Порядковий номер" are not added.
