### ISSUE TITLE
[Admin tab] The website allows you to go to the administration page after removing the token

### ISSUE THREAD

**Issue by VitaliiPopovych1408** [ita-social-projects/TeachUA#1369]
**Environment:** Windows 10 Professional, Chrome 96.0.4664.110
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev/

**Preconditions**
1. Log in as an administrator on https://speak-ukrainian.org.ua/dev/ (login: [admin@gmail.com](mailto:admin@gmail.com); password: admin)

**Steps to reproduce**
1. Press F12 to open DevTools
2. Click on 'Application' - 'Local Storage' and Clear token below
3. Go to user cabinet at top right corner - "Адміністрування" - "Користувачі"
4. Pay attention to the fact, that the logout user can go to the one of administration tabs

**Actual result**
The website allows you to go to the administration page after removing the token

**Expected result**
The website will return to the main page after deleting the access token and going to the administration page

![clear token1](https://user-images.githubusercontent.com/42620939/164674617-008e8ee7-2a44-4b30-911f-ea82df1d5dc7.png)
![clear token2](https://user-images.githubusercontent.com/42620939/164674618-4f002dc8-8e5e-4c7a-8677-60ecc5b2e8ed.png)
![clear token3](https://user-images.githubusercontent.com/42620939/164674620-bcfe1ccc-ca6f-4d78-91b6-618b9e3440c8.png)

**Comment by bakaydmytro** [comment]
@VitaliiPopovych1408 ,it is reproduced on prod?

**Comment by VitaliiPopovych1408** [comment]
> @VitaliiPopovych1408 ,it is reproduced on prod?

we do not have admin access to the prod version
