### ISSUE TITLE
[Access token] The user account token has been around for too long

### ISSUE THREAD

**Issue by VitaliiPopovych1408** [ita-social-projects/TeachUA#1370]
The user account token has been around for too long. It is necessary to reduce the lifetime of the token from 24 hours to 1-2 hour
![clear token](https://user-images.githubusercontent.com/42620939/164681128-18f52a3f-496c-4109-b04d-d450125cc2bf.png)
s

**Comment by bakaydmytro** [comment]
@softservedata , we need to agree on the lifetime of the token

**Comment by bakaydmytro** [comment]
changed lifetime token to 1 hour
