### ISSUE TITLE
[Банер] Image in baner field does not exist on production enviroment

### ISSUE THREAD

**Issue by IvanKuzmuk** [ita-social-projects/TeachUA#1374]
![1](https://user-images.githubusercontent.com/57858834/165563248-d9f083fd-d238-497b-a627-b683058f604b.PNG)
![2](https://user-images.githubusercontent.com/57858834/165563253-37f70f96-a3ac-42a7-9c1e-4b9313cdc3a6.PNG)
**Environment:** Windows 10 Pro 21H1,OS build19043.1586, Google Chrome, version 99.0.4844.84
**Reproducible:** ararely
**Build found:** last commit 

**Preconditions**
Log in as an administrator on https://speak-ukrainian.org.ua/dev/
Log in as a user on https://speak-ukrainian.org.ua/
**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on "Навчай українською" button on the upper left corner
3. Take a look at baner on the main page

**Actual result**
Not all images displayed on the banner

**Expected result**
All images displayed on the banner correctly

https://user-images.githubusercontent.com/57858834/165254772-8f6ebc1a-ffc3-49f4-a16a-cd457b2367a0.mp4

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by softservedata** [comment]
Not Bug. Do not use AdBlock
