### ISSUE TITLE
[Changing the location] The message about the lack of clubs does not appear after re-selecting a city in which there are no clubs

### ISSUE THREAD

**Issue by VitaliiPopovych1408** [ita-social-projects/TeachUA#1389]
**Environment:** Windows 10 Professional, Chrome 96.0.4664.110
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev/

**Preconditions**
1. Go to webpage https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Change location to "Луцьк" at the top right part of the site;
2. Pay attention to the result of this action;
3. Change location back to "Київ" at the top right part of the site;
4. Pay attention to the result of this action;
5. Change location back to "Луцьк" at the top right part of the site;
6. Pay attention to the result of this action;

**Actual result**
Current information is updated only for the first time after changing the location

**Expected result**
After each change of location, the page with up-to-date information is updated
![location3](https://user-images.githubusercontent.com/42620939/166425362-b0cd1b71-78af-463f-92f6-c54387b24c14.png)
![location1](https://user-images.githubusercontent.com/42620939/166425365-c6d43ce9-c7df-4b16-a0d0-fdfceec7a92f.png)
![location2](https://user-images.githubusercontent.com/42620939/166425371-584ffb31-1adc-4285-b8db-81c2a8c0fade.png)

**Comment by dtyta** [comment]
Tested. After each change of location, the page with up-to-date information is updated
