### ISSUE TITLE
[News] Add the news

### ISSUE THREAD

**Issue by OlenaOsadchaBA** [ita-social-projects/TeachUA#1392]
**As the Administrator I want to add the news so that I can inform visitors about upcoming or the latest activities**

**Description**
Provide adding new news on the Web-site

**Mock-up**
![image](https://user-images.githubusercontent.com/103151401/169045430-2ea8298a-2126-4b5a-8d60-6bdcf3289a03.png)
https://www.figma.com/file/YSXBEZfBiDNr3dgOpMhTtH/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E?node-id=377%3A2861

 **Acceptance Criteria**

1. When the Administrator clicks the 'Додати новина' the modal window 'Додати новина' opens
2. in the opened window the system should display the following fields:

<html>
<body>

Field name | Field type | Required field | Validation
-- | -- | -- | --
Дата новини| Date picker The date format should be: DD.MM.YYYY | Yes | Yes
Заголовок | Text | Yes | Yes
Текст новини | Text | Yes | No
Фото банер| Image | Yes | Yes

</body>
</html>

3. Required fields should be marked with the red symbol '*'.
4. When the modal window opens all fields should be blank and available for entering data.
5. The Administrator should have the ability to upload only one photo in the 'Фото банер' field.
6. The validation criteria for a photo:
the size is no more than 300 Kb
the available format is image type
the uploaded photo with size that is bigger then 300 Kb should be compressed to 300 Kb.
7. When the Administrator clicks on the 'Фото банер', the system should open the modal window for selecting image files. In the opened modal window:
- the system should show image files only
- only image files should be allowed for selection
9. Buttons in the modal window:

**Зберегти**
- when at least one required field is blank, should not be available
- when all required fields are filled in, the button should be available
- when the Administrator clicks the button, the system should leverage the validation process of required fields in accordance with the description User story #1393  
- when the system finishes the validation process and all required fields are correct, the system saves the news and displays the Notification flash message 'Новина додана успішно'
- the system should display the saved news on the Website (main menu Новини) User story #1405 
**Переглянути**

- when the modal window 'Додати новину' opens the button should not be available
- after the news is saved the button should be available
- when the Administrator clicks, the system should display the page with the created news (**User story** 

**Epic link**
E.g.: Epic #1379 [Epic]

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

**Comment by KostiantynStarynets** [comment]
The system works according to the requirements.
