### ISSUE TITLE
[News] Validation of required fields (news)

### ISSUE THREAD

**Issue by OlenaOsadchaBA** [ita-social-projects/TeachUA#1393]
**As the Administrator I want the system to validate required fields in the 'Додати новину', 'Редагувати новину' modal windows so that data will be correct and consistent**

**Mock-up**
https://www.figma.com/file/YSXBEZfBiDNr3dgOpMhTtH/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E?node-id=324%3A2304
![image](https://user-images.githubusercontent.com/103151401/169046739-ede4456f-c276-48b4-bddd-7ec438007d0d.png)

**Acceptance Criteria**

1. The system shall leverage the validation process of the Data in the required fields once the Administrator clicks the button 'Зберегти' in the 'Додати новину' OR 'Редагувати новину'modal windows.
2. The Data validation of fields shall perform in accordance with the rules and by the order:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/oosad/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/oosad/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72" lang=EN-US style='tab-interval:.5in;
word-wrap:break-word'>

Field   name | Validation   criteria | Validation   rules
-- | -- | --
Дата новини | Format   shall be MM.DD.YYYY | If   the field with the incorrect date format the filed should be highlighted in   red. The Administrator should see the  warning flash message: **Невірний формат дати. Формат MM.DD.YYYY**
Заголовок | Text   format     40 < number of  characters<3000 | If   the number of characters in the field is less than 40 OR more 3000 symbols,   the Administrator should see the  warning flash message: **Загловок має містити не менше 40 символів та не більше 3000**
Текст новини| Text   format     40 < number of  characters<3000 | If   the number of characters in the field is less than 40 OR more 3000 symbols,   the Administrator should see the  warning flash message: **Текст новини має містити не менше 40 символів та не більше 3000**

</body>

</html>

**Epic link**
E.g.: Epic #1379 [Epic]

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

**Comment by KostiantynStarynets** [comment]
The system works according to the requirements.
