### ISSUE TITLE
[News] View news on the Website

### ISSUE THREAD

**Issue by OlenaOsadchaBA** [ita-social-projects/TeachUA#1405]
**As a user I want to see the list of news on the Website so that I will be informed about events**

**Description**
Provide displaying news which has been added on the Website content

**Mock-up**
https://www.figma.com/file/YSXBEZfBiDNr3dgOpMhTtH/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E?node-id=439%3A4113

![image](https://user-images.githubusercontent.com/103151401/171024584-11d80c64-92ce-4c62-b571-13048565e6d2.png)

**Acceptance Criteria**

1. When a user clicks on the 'Новини' button in the main menu, the system should open the page with the list of existing news on the DB.
2. The system should display each news in a single block, which should be clickable.
3. The system should display in the block:
- the picture associated with the news (the picture from the 'Фото банер' field).
- the text from the 'Заголовок' field.
- the value from the 'Дата новини' field.
4. The picture in the block should be compressed and displayed the whole picture.
5. When the user clicks on the block OR on the 'Детальніше' button, the system should open the content page for the selected news.
6. The system should display news on the page sorted by descending date.
7. If news has the same date, the system should display the last added news on the top within the same date.
8. The page should support the pagination, 4 rows on the one page.
9. The 'Допомогти проекту' button should be available on the futer of the page and work in accordance with requierements.

**Epic link**
E.g.: Epic #1379 
**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

**Comment by bakaydmytro** [comment]
@OlenaOsadchaBA ,is it really should be 10 news block in page or 4 as a screenshot?

**Comment by KostiantynStarynets** [comment]
The system works as required. No. 1502 has been checked, it works correctly.
