### ISSUE TITLE
[News] View clubs on the News page

### ISSUE THREAD

**Issue by OlenaOsadchaBA** [ita-social-projects/TeachUA#1406]
**As a user I want to see clubs on the News page so that I will be able to acquaint with clubs while reading news** 

**Description**
Provide to show users three clubs with the highest rate within the selected location

Add mockup if needed
https://www.figma.com/file/YSXBEZfBiDNr3dgOpMhTtH/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E?node-id=439%3A4113
![image](https://user-images.githubusercontent.com/103151401/168633930-51d3846f-b39f-472f-8fca-0aff9b9c813b.png)

**Acceptance Criteria**

1. On the News page (main menu>Новини) the system should display the list of clubs for the selected location.
2. The system should display three clubs with the highest rate within the selected location.
3. The name of the list should be 'Гуртки у м. < selected location >'.
4. The system should display each club in the block, which should be clickable.
5. Once a user clicks on the block, the system should open the Card of the selected club https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A48540
6. Once a user clicks on the 'Детальніше' button, the system should open the Main club window https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A50213
7. The search of clubs should be available. If user enters the name of an existing club it will be displayed. Otherwise a not found message will be displayed.

**Epic link**
E.g.: Epic #1379 

**Labels to be added**
"User story", Correspondind Functionality (e.g. User), Priority ("pri: "), "Corresponding Epic"

**Comment by OlenaOsadchaBA** [comment]
It's acceptably to implement displaying clubs in a random order within the selected location if the rate functionality doesn't implement before
Once the rate works the order should be fixed in accordance with the p.2 of the Acceptance Criteria

**Comment by bakaydmytro** [comment]
@OlenaOsadchaBA , rating functionality works, but the club's rating does not change often, so the news page will display three same clubs and will rarely change. Maybe selecting three random clubs with a rating above average?

**Comment by OlenaOsadchaBA** [comment]
@bakaydmytro It's assumed that tach club has its rate based on the customer's reviews. As I know, this functionality has been implemented, but it doesn't work in a product enviroment. Maybe there are not enough reviews for each club to make the appopriate conclusion or maybe the activity of users to put their reviews is in a low level and that's why the rate doesn't change frequently. Does it make sense?
