### ISSUE TITLE
[Додати центр] missing Scroll Bar in location list

### ISSUE THREAD

**Issue by orezv** [ita-social-projects/TeachUA#1424]
**Environment:** Windows 10, Google Chrome Version 101.0.4951.67 (х64)
**Reproducible:** always
**Build found:** last commit

Preconditions:
Preconditions: Log into https://speak-ukrainian.org.ua/dev/ under club manager or admin user.

**Steps to reproduce:**
**Scenario 1**
1. Click on the profile drop-down list
2. Click on 'Додати центр'

**Scenario 2**
1. Click on the profile drop-down list
2. Click on 'Мій профіль'
3. Click on '+ Додати' button
4. Click on 'Додати центр'

**Actual result**
displayed location list with some part of created locations
![image](https://user-images.githubusercontent.com/104138998/171422292-e1a28f18-189c-4662-852d-b6abf9162c1e.png)

**Expected result**
displayed full location list with a vertical Scroll Bar to be able to select location from the list

User story and test case links
User story #71

**Comment by KostiantynStarynets** [comment]
Scroll Bar in location list ,added and working correctly.
![Знімок екрана 2022-12-17 222743](https://user-images.githubusercontent.com/117648097/208264956-92fa061d-3b51-4f7e-9a8d-82f1f48f3ea8.jpg)
