### ISSUE TITLE
[News] Error appears after going to the news.

### ISSUE THREAD

**Issue by dtyta** [ita-social-projects/TeachUA#1431]
Environment: Windows 10 Enterprise 21H2 , Google Chrome 102.0.5005.63.
Reproducible: always.
Build: last commit from https://speak-ukrainian.org.ua/dev/

Summary:
After clicking on the news/"Детальніше", an image of the error appears for a few seconds.

Steps to reproduce
1. Go to https://speak-ukrainian.org.ua/dev
2. Click on Новини
3. Click on first news(On image or Детальніше)

Actual result
After clicking on the news/"Детальніше", an image of the error appears for a few seconds.

Expected result
After clicking on the news/"Детальніше", 

https://user-images.githubusercontent.com/71213896/171600311-6ddc0c4b-d1c4-489b-b293-517f3eb0c41d.mp4

there is a transition to the page of the selected news without errors.

**Comment by KostiantynStarynets** [comment]
It was not possible to reproduce the error on those news items for 02.5.2022 and 12.23.2022, because they were deleted. But the sequence on other news works correctly. The error does not slip.
