### ISSUE TITLE
[News]  Title doesn't match the section "Новини"

### ISSUE THREAD

**Issue by dtyta** [ita-social-projects/TeachUA#1432]
Environment: Windows 10 Enterprise 21H2 , Google Chrome 102.0.5005.63.
Reproducible: always.
Build: last commit from https://speak-ukrainian.org.ua/dev

Actual result:
Header-"Гуртки у місті Києві" at news page.

Expected result:
Header- "Новини" at news page.

![ХедерНовини](https://user-images.githubusercontent.com/71213896/171618490-6edd748a-90d5-47a8-ad4c-25a0432d42e7.png)

**Comment by VitaliiPopovych1408** [comment]
![image](https://user-images.githubusercontent.com/42620939/171703943-192511b1-187b-4b49-a49d-b3015d06dbdd.png)
