### ISSUE TITLE
[Certificates] Certificate issuance page (v.1)

### ISSUE THREAD

**Issue by Olena-Mamchur** [ita-social-projects/TeachUA#1468]
### As an admin, I want to issue certificates to participants of the challenge

**Description**
In the administration pane, a new option Сертифікати is added. An admin shall have the ability to upload three different types of Excel files with the information about the participants of the challenge and then issue a certain type of a certificate to them. There are three types of certificates based on the type of the participant. More on certificate types here [https://github.com/ita-social-projects/TeachUA/issues/1467](url)

### Acceptance Criteria

1. When the admin selects Адміністрування, there shall be a section Сертифікати.
2. On the Сертифікати page, an administrator shall have the Завантажити excel-файл option. Test file https://docs.google.com/spreadsheets/d/1HeGE69XZjkOjsS-I-owvtAApwxwxkFm_O8TZPgNrsDI/edit#gid=0
3. After uploading the necessary Excel file, an admin shall click Відправити всі дані у БД.
4. Once the data is uploaded, the admin clicks Надіслати сертифікати.

![Admin pane certificate](https://user-images.githubusercontent.com/109747156/181740773-c4459a7a-d80f-4ed4-9443-24d4d23739af.jpg)

![Excel upload page](https://user-images.githubusercontent.com/109747156/188433512-61d516d0-5aca-49ea-9332-1674b5f4f9ba.jpg)

**Comment by KostiantynStarynets** [comment]
Everything works according to the acceptance criteria.
