### ISSUE TITLE
[Certificates] Format of the certificate: Participant

### ISSUE THREAD

**Issue by Olena-Mamchur** [ita-social-projects/TeachUA#1479]
### As an admin I want to issue a certificate for the participant of the course

After finishing a course, its participants should receive certificates. 

### Acceptance Criteria
To have a look at what content the certificate shall include, refer to the attached documents.

1. A certificate should have the following information (refer to the text in the attached doc file):

- name, surname, patronymic name (по батькові)
- length of training (40 годин)
- the responsible person or people for training (name, surname, patronymic name) Наталка Федечко, голова ГО "Українська гуманітарна платформа"
- signature of a person or people responsible for the training
- website of the initiative Навчай українською (speak-ukrainian.org.ua)
- logos attached to this user story
- date of certificate issuance (will be provided in the Excel file)

2. Font is Halvar Breitschrift, font size 24 pts.

-  "сертифікат, №" "підтверджує..", "тривалість..", "проєкт..", "голова..." - medium;
- Наталка Федечко - bold;
- ім'я власника сертифікату - black.

3. Format of the certificate is horizontal A4 page, size 210 x 297 mm.
4. A certificate shall be issued in a PDF format.
5. A received email shall have a title Сертифікат проєкту "Єдині" and a body text shall say Вітаємо! Дякуємо Вам, що долучилися до проєкту "Єдині". Дякуємо за спільну роботу задля великої мети. Ваш сертифікат додано у вкладенні до цього листа.

[Content.template.for.a.certificate.docx](https://github.com/ita-social-projects/TeachUA/files/9277521/Content.template.for.a.certificate.docx)
![Navchai UKR logo](https://user-images.githubusercontent.com/109747156/183309975-54c08cde-ef9a-4e71-80b3-6c902be127a8.jpg)
![Stamp](https://user-images.githubusercontent.com/109747156/183309977-759a90b4-5016-44d5-a98e-75abd2382cb3.jpg)
![Yedyni banner](https://user-images.githubusercontent.com/109747156/183309978-a2e14560-37e8-40d8-8491-06692e96194f.jpg)
![Mayor summit logo](https://user-images.githubusercontent.com/109747156/184378830-ff7be513-2a1b-4cbc-a29b-ef1d07ce3546.jpg)
![Ministry logo](https://user-images.githubusercontent.com/109747156/184378847-d2d832df-6abb-48bf-a44d-33c06b22580f.jpg)

<img width="670" alt="Макет сертифіката учасника 2022 09 22" src="https://user-images.githubusercontent.com/113117933/193783244-150da334-d538-4268-ab07-dcbe5a2d4876.png">

**Comment by KostiantynStarynets** [comment]
Everything works according to the acceptance criteria. "patronymic name (по батькові) - invalid, current requirements do not require this to be specified. 
![Знімок екрана 2023-02-15 210345](https://user-images.githubusercontent.com/117648097/219475771-1581ad70-1c23-4bd8-b94f-5497a3512416.jpg)
![Знімок екрана 2023-02-15 212307](https://user-images.githubusercontent.com/117648097/219475790-ee8f5e1b-472c-4fb1-a4f4-3ee34f4ca27e.jpg)
![Знімок екрана 2023-02-15 212511](https://user-images.githubusercontent.com/117648097/219475811-1addf6ed-898b-4a02-9b31-3f671096ced0.jpg)
