### ISSUE TITLE
[Affected functionality] When editing news, the date is displayed as YYYY, MM, DD

### ISSUE THREAD

**Issue by KostiantynStarynets** [ita-social-projects/TeachUA#1570]
**Environment:** Windows 11 Enterprise, Google Chrome, notebook
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev/news/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/news/
2. Click on menu- "Сторінка" - "Новини"- "Редагувати"

**Actual result**
The date is displayed "YYYY, MM, DD"
![Знімок екрана 2022-12-10 171943](https://user-images.githubusercontent.com/117648097/206866460-6277956c-3127-43ce-9642-c180dfec2515.jpg)
![Знімок екрана 2022-12-10 172115](https://user-images.githubusercontent.com/117648097/206866462-8e4db22d-b047-4ef1-803f-7142c210d54b.jpg)

**Expected result**
According to the requirements of clause 2. DD.MM.YYYY

**User story and test case links**
E.g.: "User story #1394

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by KostiantynStarynets** [comment]
Other requirements work correctly.

**Comment by VlasenkoYuliia** [comment]
not relevant
