### ISSUE TITLE
[Advanced search] Location is absent on center component in list view 

### ISSUE THREAD

**Issue by RuslanPleskun** [ita-social-projects/TeachUA#1573]
**Environment:**  Windows 11, Google Chrome Version 108.0.5359.99 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit [ac9cf7d](https://github.com/ita-social-projects/TeachUA/commit/ac9cf7dcb1def216d250faac4fbd5c0028aedfea)

**Preconditions**
1. Go to the webpage: https://speak-ukrainian.org.ua/dev/
2. Go to 'Гуртки' tab.
3. Click on 'Розширений пошук' button.

**Steps to reproduce**
1. Click on 'Центр' radio button.
2. Click on ![image](https://user-images.githubusercontent.com/82941067/207298783-bba1d712-9586-4c0f-a0c3-1cd4daedcf5f.png) to change view to list.

**Actual result**
Location is absent on center component in list view.
![image](https://user-images.githubusercontent.com/82941067/207303900-f6154838-e306-4671-ba73-91199950afbe.png)

**Expected result**
Location should have been present on center component.

**User story and test case links**
User story #274 

**Labels to be added**
"Bug", Priority ("pri: ").

**Comment by KostiantynStarynets** [comment]
![Знімок екрана 2023-03-04 234307](https://user-images.githubusercontent.com/117648097/222929921-05247b6c-fdf9-4b1f-b362-3bc30f888f19.jpg)
Everything works according to requirements.
