### ISSUE TITLE
[Advanced search] Center's rating is displayed in two lines

### ISSUE THREAD

**Issue by RuslanPleskun** [ita-social-projects/TeachUA#1574]
**Environment:** Windows 11, Google Chrome Version 108.0.5359.99 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit [ac9cf7d](https://github.com/ita-social-projects/TeachUA/commit/ac9cf7dcb1def216d250faac4fbd5c0028aedfea)

**Preconditions**
1. Go to the webpage: https://speak-ukrainian.org.ua/dev/
2. Go to 'Гуртки' tab.
3. Click on 'Розширений пошук' button.

**Steps to reproduce**
1. Click on 'Центр' radio button.
2. Click on ![image](https://user-images.githubusercontent.com/82941067/207301762-0c40fd41-1d7c-4147-84f4-cf3d8395d468.png) to change the view to list.

**Actual result**
Center's rating is displayed in two lines.
![image](https://user-images.githubusercontent.com/82941067/207303794-4bb00102-7034-45f9-ab2f-a12a885fd7a0.png)

**Expected result**
Center's rating should have been placed in one line.

**User story and test case links**
User story #274 

**Labels to be added**
"Bug", Priority ("pri: ").

**Comment by KostiantynStarynets** [comment]
Everything works according to requirements.
![Знімок екрана 2023-03-04 234952](https://user-images.githubusercontent.com/117648097/222930213-5bad95df-99e5-4eb3-b5e0-7c67f372ecec.jpg)
