### ISSUE TITLE
[Challenge: Task] 'Челендж' field is not editable while editing 'Редагувати завдання' modal window

### ISSUE THREAD

**Issue by Nadiia-Loza** [ita-social-projects/TeachUA#1723]
**Environment:** Win 11 OS, Google Chrome, 110.0.5481.104
**Reproducible:** always

**Preconditions**
1. Go to TeachUA website : https://speak-ukrainian.org.ua/dev/
2. Log in as a 'Адміністратор' (email: admin@gmail.com, password: admin)
3. Click on the user icon
4. In the dropdown menu, hover over the "Контент" and then 'Челенджі' links
5. Click on the 'Завдання' link

**Steps to reproduce**

1. Click on the 'Редагувати' button
2. Click on 'Челендж' field
3. Type anything
4. Choose <Ukraine> from a drop-down list. Try to select other values.

**Actual result**
The  'Челендж' field is not editable. 
After choosing an option (e.g. <Ukraine>) from a drop-down list, the default value ('Днипро') appears. 
![image](https://user-images.githubusercontent.com/125998038/222098241-903aef37-c547-4b37-afce-9bd9f3dfc631.png)

**Expected result**
All fields in the 'Редагувати завдання' modal window are editable.

**User story and test case links**
E.g.: "User story #1377 
[Test case](https://jira.softserve.academy/browse/TUA-647)"

**Labels to be added**
Type ("UI, "Functional")

**Comment by KostiantynStarynets** [comment]
![image](https://user-images.githubusercontent.com/117648097/226590855-bcfad3d3-6a59-458d-a10c-91dbdd0d3c7f.png)
Actual result
The 'Челендж' field  editable. All fields in the 'Оновити завдання' modal window are editable.

**Comment by Nadiia-Loza** [comment]
The issue is resolved. The 'Челендж' field is editable.
