### ISSUE TITLE
 "[Show on map] The wrong city is showed on the map, by choosing it without a course"

### ISSUE THREAD

**Issue by martalinnyk** [ita-social-projects/TeachUA#189]
**Environment:** Windows 10, Opera, Google Chrome, 88.0.4324.182, (64-bit).
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
-

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/clubs'
2. Click on 'Показати на карті'
3. Choose the city 'Львів'

**Actual result**
The map shows Rivne
<img width="900" alt="bug" src="https://user-images.githubusercontent.com/29281305/108703902-eca50c00-7513-11eb-8146-7d8d0709d88b.PNG">

**Expected result**
The map shows Lviv

**User story and test case links**
[User story](https://github.com/ita-social-projects/TeachUA/projects/3#card-53701861)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (Functional),

**Comment by ealight** [comment]
Fixed.
