### ISSUE TITLE
"[Basic search] Basic search doesn't find clubs by a name of a category when 'Enter' is pressed"

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#190]
**Environment:** Windows 10, Google Chrome, 88.0.4324.182, (64-bit).
**Reproducible:** always.
**Build found:** last commit.

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/'
2. Choose any city (E.g. 'Запоріжжя').
3. Click on 'Який гурток шукаєте?'.
4. Enter in the search field a category name (or part of a category name) of a club that is located in the selected city. (E.g. 'спортивні секції' or 'спор'),
5. Press 'Enter'.

**Actual result**
Nothing is found.
![screen2](https://user-images.githubusercontent.com/78953350/108713918-8cb56200-7521-11eb-8bd1-bfa40d61c017.jpg)
![screen3](https://user-images.githubusercontent.com/78953350/108713926-8f17bc00-7521-11eb-820e-1a658e704fa7.PNG)

**Expected result**
All clubs that refer to that category must be found.

**User story and test case links**
User story #77 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("Functional").

**Comment by ealight** [comment]
Fixed.
