### ISSUE TITLE
[Certificates]  Admin input valid value from 100 to 9999 for 'Номер курсу' field but system changes this value to 99

### ISSUE THREAD

**Issue by OksanaPyrozhok** [ita-social-projects/TeachUA#1905]
**Environment:** Windows 10, 64-bit
Opera One (101.0.4843.43)
**Reproducible:** always
**Build found:** 15.11,2023

**Preconditions**
1.Go to http://speak-ukrainian.eastus2.cloudapp.azure.com/dev/
2.Log in as an 'Керівник' ('Email'="[admin@gmail.com](mailto:admin@gmail.com)", 'Password'="admin")
3.Go to the Контент-Сертифікати-Згенерувати сертифікати

**Steps to reproduce**
1. Enter valid value into 'Номер курсу' field (100, 9999)

**Actual result**
The system doesn't accept the value in the field and changes this value to 99.

**Expected result**
Admin entered valid value from 100 to 9999 for 'Номер курсу' field.
The system accepts the value in the field and Admin can send data to the database.

**User story and test case links**
E.g.: "User story #1497 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: medium"), Type ("Functional"),

**Comment by OksanaPyrozhok** [comment]
not relevant

**Comment by VlasenkoYuliia** [comment]
not relevant
