### ISSUE TITLE
[excessive word] The excessive word "Sort" is located under the search

### ISSUE THREAD

**Issue by martalinnyk** [ita-social-projects/TeachUA#192]
**Environment:** Windows 10, Google Chrome, it's version, device (for mobile devices).
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
-

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/clubs'

**Actual result**
the excessive word "Sort" is located under the searcht
<img width="301" alt="bug2" src="https://user-images.githubusercontent.com/29281305/108720811-f2a5e780-7529-11eb-85e7-1b5692538a45.PNG">

**Expected result**
No word "Sort", under the search

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type (UI).

**Comment by ealight** [comment]
Will be fixed in next deploy.
