### ISSUE TITLE
"[Category names] Not all category names start with a lowercase letter "

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#193]
**Environment:** Windows 10, Google Chrome, 88.0.4324.182, (64-bit).
**Reproducible:** always.
**Build found:** last commit.

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/'
2. Click on 'Який гурток шукаєте'.
3. Look at the category names.

**Actual result**
A category 'Танці' starts with an uppercase letter.
![photo_2021-02-22_16-30-36РИ](https://user-images.githubusercontent.com/78953350/108722100-6d233700-752b-11eb-9e75-d90bc481b43d.jpg)

**Expected result**
All category names should have the same style and start with a lowercase letter.

**User story and test case links**
User story #77 

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI").

**Comment by ealight** [comment]
![image](https://user-images.githubusercontent.com/47300614/109019356-9675cb80-76c1-11eb-883e-8afbc4cd36f4.png) - here we have all the names with a uppercase letter. Replaced all the categories name to the uppercase letter.
