### ISSUE TITLE
[Map's button] Spelling mistake in the "Показати на карті" button

### ISSUE THREAD

**Issue by KhrystynaRudnychenko** [ita-social-projects/TeachUA#194]
**Environment:** macOS Big Sur (11.1), Google Chrome, 88.0.4324.182
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/TeachUA/projects/3

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/service'
2. Take a look at words of "Показати на карті" button.

**Actual result**
Translation mistake in the "Показати на карті" button according to the design.

<img width="1680" alt="Знімок екрана 2021-02-22 о 16 25 50" src="https://user-images.githubusercontent.com/78917926/108723794-5251c200-752d-11eb-9feb-cb084f8badea.png">

**Expected result**
According to the design should be "Показати на мапі".

<img width="1014" alt="Знімок екрана 2021-02-22 о 16 45 39" src="https://user-images.githubusercontent.com/78917926/108723951-79a88f00-752d-11eb-894f-0790ebeb7037.png">

**Additional information**
The same defect in Mozilla Firefox (ver. 85).

**User story and test case links**
E.g.: "User story #116 

**Labels to be added**
"Bug", Priority ("low"), Severity ("text"), Type ("UI").

**Comment by ealight** [comment]
Fixed.
