### ISSUE TITLE
[Basic search] The category of the workshop is not displayed on search box when searching for matching characters other than "спор" in the name and pressing "Enter".

### ISSUE THREAD

**Issue by mboiechko** [ita-social-projects/TeachUA#195]
Environment: Windows 10 pro, Opera, Google Chrome, 88.0.4324.182, (64-bit).
Reproducible: always
Build found: last commit

Steps to reproduce

1. Go to 'http://185.156.43.101:8080/'
2. Choose any city (E.g. "Київ").
3. Click on 'Який гурток шукаєте?'.
4. Enter in the search field a category name (or part of a category name) of a club that is located in the selected city. (E.g. "Танці"),
5. Press 'Enter'.

Actual result
Appropriate category was not displayed on search box when searching for matching characters other than "спор" in the name and pressing "Enter".
<img width="840" alt="Bug" src="https://user-images.githubusercontent.com/79207745/108724898-81b4fe80-752e-11eb-96ba-3dc7460e66eb.png">

Expected result
The category of the workshop is displayed on search box when searching for matching characters other than "спор" in the name and pressing "Enter".

User story and test case links
User story #77

Labels to be 
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("Functional").

**Comment by ealight** [comment]
Fixed.
