### ISSUE TITLE
"[Basic search] Basic search doesn't find relevant clubs to the city when user opens a new tab" 

### ISSUE THREAD

**Issue by Olha-IrynaKoval** [ita-social-projects/TeachUA#196]
Environment: Windows 10, Google Chrome, 88.0.4324.182, (64-bit).
Reproducible: always.
Build found: last commit.

**Steps to reproduce**
1. Go to 'http://185.156.43.101:8080/'
2. Choose any city from dropdown in top-right corner of the screen, except 'Київ' (E.g. 'Харків')
3. Click on 'Детальніше' on found club pressing scroll in order to open a new tab

**Actual result**
New tab opens city 'Київ', name of the Kharkiv's club 'Довкілля крізь призму української мови 2' and text 'Схожі гуртки у місті Київ'.
![image](https://user-images.githubusercontent.com/78918412/108767890-aa092100-755f-11eb-9ea1-91e67592ddbb.png)
![image](https://user-images.githubusercontent.com/78918412/108767927-b55c4c80-755f-11eb-95c3-da02795086e1.png)

**Expected result**
New tab opens city 'Харків', name of the Kharkiv's club 'Довкілля крізь призму української мови 2' and text 'Схожі гуртки у місті Харків'.
![image](https://user-images.githubusercontent.com/78918412/108767984-c7d68600-755f-11eb-9085-6354ea3d9a8c.png)
![image](https://user-images.githubusercontent.com/78918412/108768003-cd33d080-755f-11eb-81f9-77e10759cbfe.png)

**User story and test case links**
"User story #77"

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("High"), Type ("Functional").

**Comment by ealight** [comment]
Fixed
