### ISSUE TITLE
[Додати гурток] Spelling bug on "Add course" form in  one of categories checkbox

### ISSUE THREAD

**Issue by martalinnyk** [ita-social-projects/TeachUA#221]
**Environment:** Windows 10, Chrome 88.0.4324.190
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Мove the cursor on account icon in the upper right corner
3. Click on 'Додати гурток' button 

**Actual result**
Name of one of the categories is "Вокальна студії"
<img width="652" alt="spelling bug" src="https://user-images.githubusercontent.com/29281305/109962140-837f7e80-7cf3-11eb-8d93-73e99a3be33f.PNG">

**Expected result**
Name of one of the categories is "Вокальні студії"

**User story link**
User story #170 

**Priority:** Low
**Seveity:** Trivial
**Type:** UI

**Comment by Olha-IrynaKoval** [comment]
fixed
