### ISSUE TITLE
[Додати гурток] "Phone number" field can be filled with letters and special characters

### ISSUE THREAD

**Issue by martalinnyk** [ita-social-projects/TeachUA#226]
**Environment:** Windows 10, Chrome 88.0.4324.190
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Мove the cursor on account icon in the upper right corner
3. Click on 'Додати гурток' button 
4. Input valid values in first step ad go to second
5. Input invalid values in 'phone number' field (e.g. 'qwerty@$')

**Actual result**
The field allows inputting letters and special characters
<img width="224" alt="phonenumber" src="https://user-images.githubusercontent.com/29281305/109971373-d7439500-7cfe-11eb-8791-5e020e986a58.PNG">

**Expected result**
Error message, that the field allows only digits

**User story link**
User story #70 

**Priority:** High
**Seveity:** Medium
**Type:** Functional

**Comment by roman-perv** [comment]
1) invalid values in the 'phone number' field are still validated
![226_01](https://user-images.githubusercontent.com/83238027/117985517-714c3d00-b341-11eb-99db-99e1681e6aaf.png)

2) The 'phone number' field should be mandatory, now it's not mandatory.
