### ISSUE TITLE
[ Додати гурток]  "Вік дитини" field is not shown as required in the "Додати гурток" form after clicking "Додати гурток" menu item

### ISSUE THREAD

**Issue by katerynasyrotska** [ita-social-projects/TeachUA#228]
**Environment:** Mac OS Big Sur 11.1, browser Google Chrome 89.0.4389.82
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click the "Додати гурток" button in the upper right corner of the page.
3. Pay attention to the "Вік дитини" field in the "Додати гурток" form.

**Actual result** The ‘Вік дитини’ fields are filled by default ‘від 2 до 18’ and aren’t mandatory 
<img width="1344" alt="вік_field" src="https://user-images.githubusercontent.com/78917969/109986482-758b2700-7d0e-11eb-8b0f-dd68bb0e16fb.png">

<img width="1151" alt="Screenshot 2021-04-15 at 12 01 35" src="https://user-images.githubusercontent.com/78917969/114844337-60acb380-9de3-11eb-9087-8b4850d7b2e9.png">

**Expected result** The ‘Вік дитини’ fields are empty by default. The field that indicates the minimum age is mandatory

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI).

**Comment by roman-perv** [comment]
[Додати гурток] The color of values entered in 'Вік' and 'Опис' fields isn't contrasting #257
