### ISSUE TITLE
"[Додати гурток] Incorrect alignment of category names and numbers indicating age on the form"

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#233]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on an account icon on the right upper corner
3. Click on 'Додати гурток' button
4. Look at the alignment of category names and alignment of numbers which indicate an age

**Actual result**
Alignment is incorrect
![image](https://user-images.githubusercontent.com/78953350/110232809-b8c0e200-7f28-11eb-90d1-98d0943bba0b.png)

**Expected result**
![image](https://user-images.githubusercontent.com/78953350/110740940-840c9d80-823c-11eb-80d7-e2a8ac1f1d4b.png)

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI").

**Comment by roman-perv** [comment]
The alignment is incorrect. 
![233_01](https://user-images.githubusercontent.com/83238027/117978798-ec5e2500-b33a-11eb-9b52-5c9d0b4bd16e.png)

Duplicate categories. And one 'Категорія' checkbox without a name - delete this checkbox.  
![233_02](https://user-images.githubusercontent.com/83238027/117978831-f3853300-b33a-11eb-9b73-272861256584.png)

**Comment by OlhaPasichnyk** [comment]
Why are you writing this information to me?





ср, 12 трав. 2021, 15:59 користувач Roman Pervenets <
***@***.***> пише:
