### ISSUE TITLE
TBD[Головна сторінка]  The scroll page of 'Оберіть напрям гуртків' doesn't start with the last card from a previous scroll page

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#237]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit)
**Reproducible:** always.
**Build found:** https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Scroll down to 'Оберіть напрям гуртків' cards
3. Pay attention to the last card on the scroll page
4. Swipe to the next scroll page
5. Pay attention to the first card on this scroll page

**Actual result**
This scroll page doesn't contain the last card from a previous scroll page
![image](https://user-images.githubusercontent.com/78953350/110476603-d50c7c80-80ea-11eb-9c7a-8f9436335844.png)
![image](https://user-images.githubusercontent.com/78953350/110476699-efdef100-80ea-11eb-96db-f594002a3995.png)

**Expected result**
The scroll page should start with the last card from a previous scroll page
![image](https://user-images.githubusercontent.com/78953350/110477162-81e6f980-80eb-11eb-991c-6a00b64ce31d.png)

**User story and test case links**
E.g.: "User story #166, #108 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("UI").

**Comment by marianben** [comment]
it`s not bag
