### ISSUE TITLE
[Додати гурток] Entered values aren't saved in the fields after clicking 'Наступний крок' button

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#250]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/clubs
2. Click on an account icon on the right upper corner
3. Click on 'Додати гурток' button
4. Enter values in the fields 
5. Click 'Наступний крок' button
6. Click 'Назад' button

**Actual result**
Entered previously values has disappeared

**Expected result**
Entered previously values should be saved

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("UX").

**Comment by OlhaPasichnyk** [comment]
All fields in 'Контакти', 'Опис', uploaded 'Фото' and 'Логотип' still aren't saved after clicking on 'Назад' or 'Наступний крок' buttons.
