### ISSUE TITLE
[Додати гурток] The color of values entered in 'Вік' and 'Опис' fields isn't contrasting

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#257]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** https://speak-ukrainian.org.ua/dev/clubs

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/clubs
2. Click on an account icon on the right upper corner
3. Click on 'Додати гурток' button

**Steps to reproduce**

1. Pay attention to 'Вік' field on 'Основна інформація' step
2. Go to 'Опис' step
3. Pay attention to 'Опис' field

**Actual result**
![image](https://user-images.githubusercontent.com/78953350/111021260-bac8ec00-83d3-11eb-8f82-c64c26695c37.png)
![image](https://user-images.githubusercontent.com/78953350/111021282-dcc26e80-83d3-11eb-882f-1597c40ab5f0.png)

**Expected result**
Values in fields should be contrasting

**User story and test case links**
E.g.: "User story #70 

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("UI").

**Comment by OlhaPasichnyk** [comment]
The 'Опис' field still isn't contrasting
![image](https://user-images.githubusercontent.com/82086325/116138195-2bef0500-a6dd-11eb-8e9c-06426e18c4da.png)

**Comment by roman-perv** [comment]
1) In default state place holder text for 'Вік' field should be not contrasting (according to mock-up). And values in the 'Вік' field should become contrast after feeling the field.   
![257_01](https://user-images.githubusercontent.com/83238027/117969546-368dd900-b330-11eb-957d-fa067a3261f4.png)

2)  Place holder text for 'Опис' should be not contrasting (according to mock-up).  And the text in the 'Опис'  field should become contrast after feeling the field.
![257_02](https://user-images.githubusercontent.com/83238027/117969548-37266f80-b330-11eb-9825-54ad2c5b908a.png)

**Comment by OlhaPasichnyk** [comment]
Hi,
Mockups were done a long time ago. They are not up to date.
Igor and Yaroslav know about these my  bugs and agree with me. It's
difficult for a user to see the age.
If you have another thoughts, you are welcome to speak up.

Have a nice day!
Olga

ср, 12 трав. 2021, 14:43 користувач Roman Pervenets <
***@***.***> пише:
