### ISSUE TITLE
Розширений пошук

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#274]
As a user, I want to find a club or a center using advanced search.

**Description:**

Advanced search can be opened by clicking an icon near ‘Який гурток шукаєте?’ search field. 
A hint 'Розширений пошук' is displaying while hovering on an icon.

The icon is available on ‘Гуртки’, ‘Новини’ pages and the main page. 
If the icon is clicked on the ‘Гуртки’ page, then the parameters for advanced search appear on the left side of the page.
If the icon is clicked on the main page or ‘Новини’ page, the user will be redirected to the ‘Гуртки’ page and parameters for the advanced search will appear on the left side of the page.
**Parameters:**

**‘Гурток/Центр’**

- Two radio-buttons: ‘Гурток’ and ‘Центр’
- The default setting in the ‘Гурток/Центр’ radio-button is ‘Гурток’

**‘Місто’**

- Single choice
- The default city is a city that was previously selected by a user

**‘Район міста’**

- Single choice

**‘Найближча станція метро’**

- Multiple choice among the list of metro stations

**'Доступний онлайн'** checkbox

- Find clubs that have online option
- When a user selects ‘Центр’ radio-button in ‘Гурток/Центр’, the parameter ‘Online’ is deactivated

**‘Категорія’**

- Multiple choice among the list of categories
- When a user selects ‘Центр’ radio-button in ‘Гурток/Центр’, the parameter ‘Категорія’ is deactivated

 

**‘Вік дитини’** input:

- optional
- is empty by default
- accepts only positive integers from 2 to 18 
- When a user selects ‘Центр’ radio-button in ‘Гурток/Центр’, the parameter ‘Вік дитини’ is deactivated

Search results are loaded automatically after selecting a criterion.
All parameters are optional, but at least one parameter must be selected.

Search results can be sorted alphabetically or by rating.
Search results can be displayed as a grid or as a list.

**AC:**
-A user can find a club using advanced search by filling in at least one parameter
-A user can see the results of the search
-A user can change chosen parameters to others and see the updated results of the search

Frames on Figma: 560, 561, 562, 563.

<img width="960" alt="Advanced search" src="https://user-images.githubusercontent.com/32505957/117717635-bbb7a780-b1e3-11eb-9f33-8be28ff23285.png">

**Comment by DmytroKarman** [comment]
opened bugs:
#615
#613
#612

**Comment by Ytrygub** [comment]
User story has been updated according to the mentor's approve
