### ISSUE TITLE
[Додати гурток] A location(s) that was added to a club isn't saved after clicking 'Наступний крок' button

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#307]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit https://speak-ukrainian.org.ua/dev/clubs

**Preconditions**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page
3. Fill/choose all mandatory parameters on 'Основна інформація' step and click on 'Наступний крок' button 

**Steps to reproduce**

1. Click on 'Додати локацію' on 'Контакти' step
2. Fill all mandatory fields on 'Додати локацію' pop-up and click 'Додати' button
3. Click 'Наступний крок' button
4. Click 'Назад' button

**Actual result**
A location that was added has disappeared 

**Expected result**
A location should be saved on 'Контакти' step after moving to the next step and should be present when we return to this step

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UX").

**Comment by OlhaPasichnyk** [comment]
The location is saved on the 'Контакти' step, but if the user opens to edit it, the street isn't saved in 'Адреса' field.
![image](https://user-images.githubusercontent.com/82086325/116141441-593db200-a6e1-11eb-8942-e43d88f4ed9c.png)
![image](https://user-images.githubusercontent.com/82086325/116141469-62c71a00-a6e1-11eb-9380-75a2f2bc124d.png)

**Comment by roman-perv** [comment]
Main issue "A location(s) that was added to a club isn't saved after clicking 'Наступний крок' button" already fixed. Additional issue "The location is saved on the 'Контакти' step, but if the user opens to edit it, the street isn't saved in 'Адреса' field." is duplicated with issue [#309](https://github.com/ita-social-projects/TeachUA/issues/309) "An address of a location isn't shown on the pop-up after adding a location".
