### ISSUE TITLE
[Додати локацію] An address of a location isn't shown on the pop-up after adding a location

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#309]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Preconditions**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page
3. Fill/choose all mandatory parameters on 'Основна інформація' step and click on 'Наступний крок' button

**Steps to reproduce**

1. Click on 'Додати локацію' on 'Контакти' step
2. Fill all mandatory fields on 'Додати локацію' pop-up and click 'Додати' button
3. Open pop-up with this location again to edit it
4. Pay attention to 'Адреса' field

**Actual result**
An address of a location has disappeared
![image](https://user-images.githubusercontent.com/78953350/113247329-7c806780-92c3-11eb-8566-49021c52f857.png)

**Expected result**
An address of a location should be present on the pop-up

**User story and test case links**
User story #70, #291 

**Labels to be added**
"Bug", Priority ("pri: low"), Severity ("severity: minor"), Type ("Functional").

**Comment by roman-perv** [comment]
Location address is saved, but text not contrast. 

![309_01](https://user-images.githubusercontent.com/83238027/118081674-7e5e4000-b3c4-11eb-9510-669d82ec359c.png)
