### ISSUE TITLE
[Головна сторінка] Wrong spacing between blocks

### ISSUE THREAD

**Issue by KhrystynaRudnychenko** [ita-social-projects/TeachUA#324]
**Environment:** macOS Big Sur 11.1, Google Chrome 89.0.4
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to 'https://speak-ukrainian.org.ua/dev/ 
2. Use a page ruler and measure the size between different blocks (e. g., extension for browser).
3. Take a look at the size between blocks.

**Actual result**
Wrong spacing between blocks.

<img width="1288" alt="Знімок екрана 2021-04-03 о 23 20 18" src="https://user-images.githubusercontent.com/78917926/113490869-8c6f9580-94d5-11eb-9e43-778689c3c016.png">

<img width="1491" alt="Знімок екрана 2021-04-03 о 23 22 17" src="https://user-images.githubusercontent.com/78917926/113490900-b9bc4380-94d5-11eb-9bd8-43ed616ee622.png">

<img width="1399" alt="Знімок екрана 2021-04-03 о 23 26 40" src="https://user-images.githubusercontent.com/78917926/113490932-eec89600-94d5-11eb-83ea-f60b7d86c9c3.png">

<img width="1146" alt="Знімок екрана 2021-04-03 о 23 26 04" src="https://user-images.githubusercontent.com/78917926/113490917-d48eb800-94d5-11eb-8d24-ddc754e8c047.png">

**Expected result**
Spacing between blocks should be as on the mock-ups.

<img width="1070" alt="Знімок екрана 2021-04-03 о 23 21 27" src="https://user-images.githubusercontent.com/78917926/113490871-8f6a8600-94d5-11eb-9f96-7e37acb73f7a.png">

<img width="1049" alt="Знімок екрана 2021-04-03 о 23 23 51" src="https://user-images.githubusercontent.com/78917926/113490905-bd4fca80-94d5-11eb-8ccf-821ac2faeaa0.png">

<img width="1038" alt="Знімок екрана 2021-04-03 о 23 27 58" src="https://user-images.githubusercontent.com/78917926/113490937-f12af000-94d5-11eb-91a2-7e110677f4d1.png">

<img width="1066" alt="Знімок екрана 2021-04-03 о 23 25 17" src="https://user-images.githubusercontent.com/78917926/113490914-d193c780-94d5-11eb-9450-1ad9c432aba6.png">

**User story and test case links**
E.g.: "User story #108 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("UI")

**Comment by softservedata** [comment]
Not a bug.  Page is flexible.
