### ISSUE TITLE
[Показати на мапі] Pop-up with club`s information is not shown after multiple clicking on different places 

### ISSUE THREAD

**Issue by IZvarchuk** [ita-social-projects/TeachUA#333]
**Environment:** Windows 10 Pro, Google Chrome Version 88.0.4324.182.
**Reproducible:** sometimes
**Build found:** last commit 

**Steps to reproduce**
1. Go to 'Гуртки' page (https://speak-ukrainian.org.ua/dev/clubs)
2. Click on 'Показати на мапі' button
3. Click on club`s location pin
4. Click on another place sign
5. Click on previous club`s location pin

**Actual result**
Pop-up with club`s information is not shown

https://user-images.githubusercontent.com/78938187/114068452-9c58f200-98a6-11eb-8e42-2bdc4ab963e8.mp4

**Expected result**
Pop-up with club`s information is shown
![Screenshot_73](https://user-images.githubusercontent.com/78938187/114068425-92cf8a00-98a6-11eb-98d2-f0ad1b0659ec.png)

**User story and test case links**
User story #116 

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: medium"), Type ("Functional")

**Comment by NataliiaYendrushchak** [comment]
re-opened

**Comment by NataliiaYendrushchak** [comment]
re-opened
