### ISSUE TITLE
[Мій профіль] The club's location is not shown on the club's card

### ISSUE THREAD

**Issue by Olha-IrynaKoval** [ita-social-projects/TeachUA#349]
**Environment:** Windows 10, Google Chrome, 88.0.4324.182, (64-bit).
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev

**Steps to reproduce**
1. Go to 'https://speak-ukrainian.org.ua/dev' and login as 'Керівник'
2. Click on 'Мій профіль'
3. Look at the club's card

**Actual result**
![image](https://user-images.githubusercontent.com/78918412/114521306-f8c36500-9c4a-11eb-9bc0-7c1e112728fd.png)

**Expected result**
![image](https://user-images.githubusercontent.com/78918412/114521444-15f83380-9c4b-11eb-8397-470e4f0806fd.png)

**User story and test case links**
User story #TBD

**Labels to be added**
"Bug", Priority ("medium"), Severity ("major"), Type ("Functional").

**Comment by roman-perv** [comment]
The club's location is not shown on the club's card.
![02](https://user-images.githubusercontent.com/83238027/118853073-0a4bfc80-b8dc-11eb-8024-4ecf4652d016.png)
