### ISSUE TITLE
[Додати гурток] The 'Назва' field doesn't have restrictions on entered characters

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#358]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page or in user's private office
3. Enter less than 5 characters/ more than 100 charachers/ not Ukrainian or English letters in 'Назва' field

**Actual result**
A club is created if the 'Назва' field contains less than 5 characters/ more than 100 charachers/ not Ukrainian or English letters

**Expected result**
'Назва' field should contain only Ukrainian and English letters, numbers and reserved characters.  Min 5 characters and max 100 characters should be allowed to be entered.

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity:medium"), Type ("Functional").

**Comment by jekBas** [comment]
https://github.com/ita-social-projects/TeachUA/issues/364

**Comment by roman-perv** [comment]
Defects:
The system allows less than 5 and more than 100 characters
Not Ukrainian and English letters allowed (e.g. 'Ü,Ы,ы,Ä,Ö,Э')
