### ISSUE TITLE
TBD[Додати гурток] ‘Telegram’, ‘Viber’, ‘Instagram’ fields are absent on the 'Контакти' step

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#361]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page or in user's private office
3. Fill all mandatory parameters on 'Основна інформація' step and move to 'Контакти' step
4. Pay attention to the fields on 'Контакти' step

**Actual result**
‘Telegram’, ‘Viber’, ‘Instagram’ fields are absent
![image](https://user-images.githubusercontent.com/78953350/114704022-c2f7ac80-9d2e-11eb-8d1e-327b70a07319.png)

**Expected result**
‘Telegram’, ‘Viber’, ‘Instagram’ fields should be present 
![image](https://user-images.githubusercontent.com/78953350/114704209-02be9400-9d2f-11eb-8bb6-624a13c9b107.png)

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: major"), Type ("Functional").

**Comment by marianben** [comment]
perfect fix
