### ISSUE TITLE
[Додати гурток] There is a switch instead of 'Доступний онлайн' checkbox on 'Контакти' step

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#362]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page or in user's private office
3. Fill all mandatory parameters on 'Основна інформація' step and move to 'Контакти' step

**Actual result**
There is a switch 
![image](https://user-images.githubusercontent.com/78953350/114706188-57630e80-9d31-11eb-99a4-ba3a3f5c37d3.png)

**Expected result**
There should be 'Доступний онлайн' checkbox instead of a switch
![image](https://user-images.githubusercontent.com/78953350/114706883-3c44ce80-9d32-11eb-99a1-00653e4574e6.png)

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: low "), Severity ("severity: medium"), Type ("UI").

**Comment by OlhaPasichnyk** [comment]
The 'Доступний онлайн' should be a switch.
