### ISSUE TITLE
[Додати гурток] The 'Опис' field doesn't have restrictions on the entered characters

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#363]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page or in user's private office
3. Enter less than 40 characters/ more than 1500 charachers/ not Ukrainian or English letters in 'Опис' field

**Actual result**
A club is created if the 'Опис' field contains less than 40 characters/ more than 1500 charachers/ not Ukrainian or English letters

**Expected result**
'Опис' field should contain only Ukrainian and English letters, numbers and reserved characters. Min 40 characters and max 1500 characters should be allowed to be entered.

**User story and test case links**
User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: medium"), Type ("Functional").

**Comment by roman-perv** [comment]
Should be validated, but now restricted:
- Some special characters (e.g.@#$(){}[]%^&). 
- If space the lat character 
- Moving to a new line with 'Enter' 

Should be restricted, but now validated:
- More than 1500 characters

**Comment by MartaFisher** [comment]
A club is created if the 'Опис' field contains less than 40 characters but only if text contain spaces.

**Comment by roman-perv** [comment]
![31](https://user-images.githubusercontent.com/83238027/120863316-033b1480-c593-11eb-95c6-38978112377c.png)

**Comment by tetianaperv** [comment]
The 'Опис' field has restrictions on the entered characters 
Another UI bug is detected: incorrect formatting of text in field 'Опис'
![Опис 1500 знаків](https://user-images.githubusercontent.com/84688181/122465695-130a1e00-cfc1-11eb-928f-61ce160de0de.gif)
