### ISSUE TITLE
[Додати локацію] The 'Назва' field doesn't have restrictions on entered characters

### ISSUE THREAD

**Issue by UlianaKondratiuk** [ita-social-projects/TeachUA#364]
**Environment:** Windows, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always.
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Додати гурток' button on the main page
3. Fill/choose all mandatory parameters on 'Основна інформація' step and click on 'Наступний крок' button
4. Click on 'Додати локацію' on 'Контакти' step
5. Enter less than 5 characters/ more than 100 charachers/ not Ukrainian or English letters in 'Назва' field on 'Додати локацію' pop-up 

**Actual result**
'Назва' field allows less than 5 characters/ more than 100 charachers/ not Ukrainian or English letters

**Expected result**
'Назва' field should contain only Ukrainian and English letters, numbers and reserved characters. Min 5 characters and max 100 characters should be allowed to be entered.

**User story and test case links**
User story #291 

**Labels to be added**
"Bug", Priority ("pri:low "), Severity ("severity: minor"), Type ("Functional").

**Comment by roman-perv** [comment]
Defects:
The system allows 4 and more than 100 characters
Reserved characters (!"#$%&'()*+,-./:;<=>?@[]^_`{}~) not allowed
