### ISSUE TITLE
[Додати челендж]

### ISSUE THREAD

**Issue by NataliiaYendrushchak** [ita-social-projects/TeachUA#370]
**As a ‘Керівник’ I want to add my challenge and information about the challenge on the website, so that an added challenge was present on the website.**

**Jira User story+test cases**
https://jira.softserve.academy/projects/TUA/issues/TUA-518?filter=allopenissues

**Description**
**‘Додати челендж’** is added to the ‘+Додати’ drop-down below the ‘Додати центр’ option available only for ‘Керівник’ role.
After clicking ‘Додати челендж’ button the **‘Додати челендж’ pop-up** is opened with the following elements: 

******‘Основна інформація’** tab**:**
-  **‘Назва Челенджу’** field, required, max: 30 characters, uniqueness;
- **‘Баннер’** file picker, size height: 400px; width: 1268px; border-radius: 8px; image size up to 600 KB. If the initial photo size is more than 600 Kb, its size must be compressed to 600 Kb during uploading a photo for the site. If a photo isn’t added, then the banner is set by default.

****‘Опис’** tab:**
- **‘Опис’** field, required, [40 – 1500] characters;
- **‘Фото’** file picker, must not exceed 300 Kb. If the initial photo size is more than 300 Kb, its size must be compressed to 300 Kb during uploading a photo for the site.
- **‘Відео’** file picker, should be viewed from a YouTube player

****‘Завдання челенджу’** tab:**
- **‘Завдання челенджу’** field, required, max: 100 characters.
- **‘Фото завдання челенджу’** file picker, size up to 600 KB. If the initial photo size is more than 600 Kb, its size must be compressed to 600 Kb during uploading a photo for the site. If a photo isn’t added, then a card of the carousel is set by default.

****‘Наступний крок’** button:**
- Enabled - only when all mandatory fields are filled;
- Disabled - if at least one of the mandatory fields is still empty;
- After click user is navigated to the next tab if no see the table below;

****‘Назад’** button** – user is navigated to the previous tab/page;
****‘Завершити’** button** – challenge is created if no see the table below.

Field / file picker | Condition | Messages
-- | -- | --
‘Назва Челенджу’ | forbidden characters | ‘Це поле може містити тільки українські та англійські   літери, цифри та спеціальні символи’|
_ | less than 1 characters | ‘Поле ‘Назва Челенджу’ не може бути   порожнім’
_ |more than 30 characters | ‘Назва Челенджу задовга’
‘Баннер’ | photo isn’t added | ‘Ви не додали фото для   баннера. Фото буде встановлено за замовчуванням’
‘Опис’ | forbidden characters | ‘Це поле може містити   тільки українські та англійські літери, цифри та спеціальні символи’
_ |less than 40 characters | ‘Опис Челенджу закороткий’
_ |more than 1500 characters | ‘Опис Челенджу задовгий’
‘Завдання челенджу’ | forbidden characters | ‘Це поле може містити   тільки українські та англійські літери, цифри та спеціальні символи’
_ |more than 100 characters | ‘Завдання челенджу задовге’
_ |less than 1 character | ‘Поле ‘Завдання   челенджу’ не може бути порожнім’
‘Фото завдання челенджу’ | photo isn’t added | ‘Ви не додали фото для завдання челенджу. Фото буде   встановлено за замовчуванням’

### Acceptance Criteria

1. ‘Керівник’ can add a challenge with all mentioned parameters
2. It’s impossible to add a challenge without filling in all mandatory fields
3. It’s possible to add a challenge without filling in optional fields
4. All info about the added challenge can be found in the database and on the website

**Labels to be added**
"User story"

![Буфер обміну01](https://user-images.githubusercontent.com/81984844/115021727-03892e80-9ec5-11eb-9541-1332711937df.jpg)

![first step](https://user-images.githubusercontent.com/81984844/117954250-83b57f00-b31f-11eb-9d31-bb938533c98b.png)

![second step](https://user-images.githubusercontent.com/81984844/117954255-844e1580-b31f-11eb-907e-eda0b244c8ce.png)

![third step](https://user-images.githubusercontent.com/81984844/117954256-844e1580-b31f-11eb-8880-0ba84409cdd4.png)

**Comment by ShisenSni** [comment]
### UPDATE 11.02.21
1. **Admin** - Role which can create challenges.
2. "Додати челендж" Button is added to page "Челенджі" which can opened by click on "avatar" button then bend over "Адміністрування", and click "Челенджі"
<img width="1319" alt="Screenshot 2022-02-11 at 02 18 05" src="https://user-images.githubusercontent.com/96551212/153518854-99e736b6-d7d0-4d0c-bdb8-6f1ee3957437.png">

3. "Додати челендж" button open page "Додати челендж"
<img width="1312" alt="Screenshot 2022-02-11 at 02 17 11" src="https://user-images.githubusercontent.com/96551212/153518769-748e11dd-646e-421f-af18-39103579dcb8.png">
4. All previous version of tabs is removed (‘Основна інформація’ tab, 'Опис’ tab, ‘Завдання челенджу’ tab.)
5. New mandatory text field "Порядковий номер" need to contain integer numbers.
6.  Error massages in English.
