### ISSUE TITLE
[Header]

### ISSUE THREAD

**Issue by IrynaKahanyak** [ita-social-projects/TeachUA#371]
**As a user** (any role), **I want** to see top navigation bar in the header of the home page **so that** I can navigate through the site

**Description:**
Header should be displayed in the top of the page and allow navigation through site. It consists of upper part where are located: **logo “Навчай українською”**, **“Гуртки”**, **“Челендж”**, **“Новини”**, **“Проєкт”** and **“Послуги українською”** tabs; **“Location”** dropdown; **“Додати гурток”** button and **“Login”** button. At the lower part of the header following elements are located: **“Ініціатива ‘Навчай українською’”** label and the **“Search”** field. The user is able to see header on all the pages of the site in the same form as in the main page, except **“Проєкт”** page, article pages and **“Послуги українською”** page, on those pages lower part of header is not displayed. The header corresponds to mock-ups. 
Header items | Acceptance criteria
---------------|----------------------
Logo “Навчай українською” | ·           When click   on the logo the Home page is opened. (When user is on another pages as well)
The “Гуртки” tab  <br /> “Челендж” tab  <br /> “Новини” tab  <br /> “Проєкт” tab <br />  “Послуги українською” tab | ·           When click   on “Гуртки”/”Челендж”/”Новини”/”Проєкт”/”Послуги українською” user should be redirected to “Гуртки” ”/”Челендж”/”Новини”/”Проєкт”/”Послуги украінською” page  <br />  ·           When open   this tab, the label is underlined and when return to the main page the   underline disappears
Location item | ·           Location item should contain icon (according to the mock-up) and the dropdown   menu with list of cities (should be defined later)  <br />  ·           “Kyiv” should be selected by default
The “Додати гурток” button | ·           It should be clickable <br />  ·           When you click on the “Додати гурток” button a pop-up(modal window) “Додати   гурток” appears with the option of editing   clubs
The login item | ·           The login item should contain icon and the dropdown menu <br />  ·           For unregistered users: the login icon is without background and in dark orange color <br />   ·           For registered users: the login icon is with an avatar according to mock-ups <br />  ·           Dropdown menu near the   login icon for unregistered users contains such items:   "Зареєструватися", "Увійти"  <br />  ·           Dropdown menu for   registered users contains such items: "Мій профіль",   "Вийти"
The “Ініціатива “Навчай українською” label | ·           Should be simple label  <br /> ·           Font: Open Sans, size: 32px, line height: 24px
The search field | ·           The search field is present on all pages (except “Проєкт”, article pages and “Послуги украінською” page)  <br /> ·           Until user starts typing   text, the user sees the placeholder “Який гурток шукаєте?”. When the user starts typing text, the placeholder disappears   <br /> ·           On the right side near the   search field “advanced search” item is present. Related to story [https://github.com/ita-social-projects/TeachUA/issues/274](url)  <br />  ·           When click on search field dropdown following suggestions appears <br />  ·           Dropdown suggestion should contain of “Категоріі” and “Гуртки” sections with list of categories   and clubs <br />  ·           When start typing text in search field clear icon appears  <br />  ·           When click on “advanced search” button section for advanced search “Розширений пошук” should be displayed on the left side of the page <br />  ·           When click on “advanced search” button second time “Розширений пошук” section should disappear 

**Acceptance criteria:**
The page corresponds to the mock-up and functionality corresponds to the requirements
The user is able to click on all available items and all corresponding pages will be opened
The user has a possibility to search for “Який гурток шукаєте?” in site in a search field
The user is able to choose any city in location dropdown menu. If the user doesn’t choose any city - Kyiv is by default
The user is able to log in and log out by clicking on login item. Items: "Зареєструватися", "Увійти" is available for unregistered users;  and items: "Мій профіль", "Вийти" is available for registered users.

Mockup:
![2](https://user-images.githubusercontent.com/82086426/116147689-b2f5aa80-a6e8-11eb-835f-02b7b1edae65.png)

**Comment by Natalia96255** [comment]
The search field is present on all pages
