### ISSUE TITLE
[Розширений пошук] Website crashes when 'Без локації' option is selected in advanced search

### ISSUE THREAD

**Issue by VovaHordinets** [ita-social-projects/TeachUA#392]
**Environment:** Windows, Google Chrome 90.0.4430.85 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** https://speak-ukrainian.org.ua/dev/

**Steps to reproduce:**
1. Go to "https://speak-ukrainian.org.ua/dev/"
2. Open 'Гуртки' page
3. Click on advanced search icon to open advanced search
4. Select 'Без локації' option in the ‘Місто’ dropdown list 

**Actual result**
Website crashed.**TypeError: Cannot read property 'city' of undefined** is shown  in the console
![image](https://user-images.githubusercontent.com/32505957/116141976-09131f80-a6e2-11eb-9e92-5613f2caf69e.png)

**Expected result**
 It should be possible to apply advanced search for clubs without location

**User story and test case links**
E.g.: "User story #274 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: Critical"), Type ("Functional").

**Comment by IrynaKahanyak** [comment]
[https://github.com/ita-social-projects/TeachUA/issues/394](url)
