### ISSUE TITLE
[Показати на мапі] 'Всі міста' and 'Всі категорії' are not displayed by default in the dropdown list

### ISSUE THREAD

**Issue by IrynaKahanyak** [ita-social-projects/TeachUA#415]
**Environment:** Windows 10, Chrome 90.0.4430.85
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Show on map'
3. Observe a dropdown 'Всі міста' and 'Всі категорії'

**Actual result**
‘Киів’ and 'Empty category' are displayed by default instead ‘Всі міста‘ and ‘Всі категоріі’
![9](https://user-images.githubusercontent.com/82086426/116621356-b6d53700-a94b-11eb-8011-240c1c13452d.png)

**Expected result**
'Всі міста' and 'Всі категорії' should be displayed by default in the dropdown list
![8](https://user-images.githubusercontent.com/82086426/116621373-bc328180-a94b-11eb-81a4-e74fc2fcdce6.png)

**User story and test case links**
E.g.: "User story #116 

**Labels to be added**
"Bug", Priority ("Medium"), Severity ("low"), Type ("Functional")

**Comment by Kindrat02** [comment]
According to our product owner, the "City" field in the drop-down list should contain the value stored in the right corner of the main page.

**Comment by MaryanaUstymenko** [comment]
Fixed in build 27.05.2021 [https://speak-ukrainian.org.ua/dev/](https://speak-ukrainian.org.ua/dev/)
![2021-05-27_23h30_31](https://user-images.githubusercontent.com/83178616/119893105-a660ae00-bf43-11eb-8b9f-92e3a3df525e.png)
