### ISSUE TITLE
[Affected functionality] Advanced search

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#427]
Browser: Microsoft Edge
Device: HP ProBook 440 G7

Actual behavior: Sorting panel changes extends when screen size is 14"
![image](https://user-images.githubusercontent.com/83717595/117783029-d96c2780-b24a-11eb-988e-f187d7ab4696.png)

Expected behavior: sorting panel should be centralized, shouldn't merge with filters sidebar menu

**Comment by softservedata** [comment]
Add Border/Padding
