### ISSUE TITLE
[Affected functionality] Footer

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#468]
Browser: Microsoft Edge
Device: HP ProBook 440 G7

Actual behavior: footer re-groups in the screen's size 14''
![image](https://user-images.githubusercontent.com/83717595/119150063-c3cedd00-ba56-11eb-81a4-6526e637f4ff.png)
 Expected behavior: icons' and text's placement shouldn't change

**Comment by mpetliak** [comment]
Reported issue: Мова об'єднує, Є-мова icons are blurred when monitor is small. Should be checked additionally

**Comment by marianben** [comment]
skipping text in text to help project
