### ISSUE TITLE
[Club's page] Map is a picture and it doesn't display the actual location

### ISSUE THREAD

**Issue by roman-perv** [ita-social-projects/TeachUA#472]
**Environment:** Windows 10, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on ''Гуртки" section
3. Pick any clubs card with location and click on 'Детальніше' 
4. Pay attention to the map in the right upper corner

**Actual result**
The map is a picture and it doesn't display the actual location. 

![06](https://user-images.githubusercontent.com/83238027/119272793-75fdd480-bc10-11eb-84e2-080cf51c1a0b.png)

**Expected result**
The map is interactive and displays the actual location.
Like 'Показати на мапі'

![07](https://user-images.githubusercontent.com/83238027/119272797-7dbd7900-bc10-11eb-832d-8caadbb2da36.png)

 

**User story and test case links**
E.g.: "User story  

**Labels to be added**
"Bug", Priority ("pri: medium"), Severity ("severity: minor"), Type ("Functional").

**Comment by softservedata** [comment]
Створити карту з позначкою гуртка на властивостях гуртка

**Comment by roman-perv** [comment]
Blocked by bug #528
