### ISSUE TITLE
[Розширений пошук] The search option for online clubs is not performed if the city is differrent from Київ

### ISSUE THREAD

**Issue by OstapLudchak** [ita-social-projects/TeachUA#483]
Environment: Google Chrome 89.0.4389.90, Windows 10
Reproducible: always
Build found: last commit from https://speak-ukrainian.org.ua/dev/

Steps to reproduce:

1. Go to https://speak-ukrainian.org.ua/dev/
2. Open 'Гуртки' page
3. Click on advanced search button to open advanced search
4. Select any city except 'Київ'
5. Select checkbox 'Доступний онлайн'

Actual result:
Clubs that have online option are not found. Notafication message 'За критеріями пошуку гуртків не знайдено' is displayed.

Expected result:
Clubs that have online option are found

**Comment by softservedata** [comment]
Not bug
