### ISSUE TITLE
[Показати на мапі] Text truncation and wrong alignment on items list

### ISSUE THREAD

**Issue by MartaFisher** [ita-social-projects/TeachUA#514]
Environment: macOS Catalina 10.15.7, Google Chrome (90.0.4430.212)
Reproducible: always.
Build found: last commit.

Steps to reproduce

1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Всі гуртки'
3. Click on 'Показати на мапі'
4. Click on 'Дніпро' on the city list

Actual result
Truncation of the address and the name of item and wrong alignment
![Знімок екрана 2021-05-30 о 19 59 51](https://user-images.githubusercontent.com/83167973/120113678-3856f980-c184-11eb-865d-a9a73d48e8fb.png)

Expected result
Address is located under the name of item and right alignment

Labels to be added
"Bug", Priority ("pri: High"), Severity ("severity:Minor"), Type ("UI).

**Comment by softservedata** [comment]
Trunc text ...
