### ISSUE TITLE
[New Club not Created] Error Creating Club

### ISSUE THREAD

**Issue by softservedata** [ita-social-projects/TeachUA#518]
**Environment:** Windows 10, Google Chrome 88.0.4324.190 (64-bit).
**Reproducible:** always
**Build found:** last commit from https://speak-ukrainian.org.ua/dev/clubs

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/ and login as admin
2. Click on 'Додати гурток' button on the main page or in user's private office
3. Fill all mandatory parameters on 'Основна інформація', 'Контакти' and 'Опис'
4. Click 'Завершити' button
5. Go to 'Мій профіль'

**Actual result**
The club is not added. 

**Expected result**
The club is added. 

**User story and test case links**
E.g.: "User story #70 

**Labels to be added**
"Bug", Priority ("pri: high"), Severity ("severity: minor"), Type ("UI","Functional")

**Comment by tetianaperv** [comment]
User can't create a new club when all mandatory fields are filled. Reproducible with the same steps.
