### ISSUE TITLE
Admin. Update/Delete Organization (Club) from card

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#571]
As an Admin I want to delete/update Organization from the card so that I don't need to navigate to admin pannel

Mockups:
![image](https://user-images.githubusercontent.com/83717595/123049507-4c4eed80-d408-11eb-9c0e-d1bbef2ea094.png)

Acceptance criteria

1. Admin can update organization from the card.
2. Admin can delete organization from the card.
3. When Admin deletes organization, admin sees a confirmation pop-up with Yes/Cancel options (screenshot is taken from Mobile)

![image](https://user-images.githubusercontent.com/83717595/123257023-4d604780-d4fa-11eb-9466-2c59fe7d27b6.png)
4. When Admin updates organization, admin is redirected to the modal Редагувати гурток
![image](https://user-images.githubusercontent.com/83717595/123050676-9f757000-d409-11eb-85f0-25176a9a462f.png)

**Comment by andriysavinof** [comment]
Edit Club functionality is not ready at the moment. Could you please create a new issue and assign it to Roman (rjone10)
