### ISSUE TITLE
Mobile. Home page view

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#572]
As a user I want to be able to see the site home page in the mobile view so that I could navigate to it from my phone

Mockups:
**Main** https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A189353

Acceptance criteria

1. User sees current state of web page in the mobile view
2. User can scroll down the page, vertical scroll is shown when page is scrolled down-scrolled up

BA notes:
Please see dimensions for mobile screen in Figma

**Comment by Natalia96255** [comment]
Header allignment

**Comment by Natalia96255** [comment]
Issue with bugrer menu

**Comment by Natalia96255** [comment]
The same bug #603
