### ISSUE TITLE
Mobile. Home page. Carousel

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#573]
As a user I want to see Оберіть напрям гуртків carousel on the Home page so that I could navigate to it from my phone

Acceptance criteria

1. User can swipe right/left the carousel  Оберіть напрям гуртків on the Home page
2. User can navigate the advanced search from the card in the carousel (same logic as for web)

BA notes:
There is a design bug 
![image](https://user-images.githubusercontent.com/83717595/123052484-8b327280-d40b-11eb-9d29-ef46ab0fa4c2.png)
**Carousel should look like**
![image](https://user-images.githubusercontent.com/83717595/123052607-b026e580-d40b-11eb-9cab-5fd1c85e0701.png)

**Comment by marianben** [comment]
addit in mobile page main frame

**Comment by MaryanaUstymenko** [comment]
mockup for mobile home page carousel 
![123052484-8b327280-d40b-11eb-9d29-ef46ab0fa4c2 mobile Home page](https://user-images.githubusercontent.com/83178616/123395521-f6fe1200-d5a8-11eb-93cc-cfc5de80838b.png)
