### ISSUE TITLE
[Реєстрація користувача] User can not register via Google account 

### ISSUE THREAD

**Issue by KrnM** [ita-social-projects/TeachUA#576]
**Environment:** Windows 10 + Chrome (Version 91.0.4472.77(64-bit))
**Reproducible:** always
**Build found:**  last commit from https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**

- Go to https://speak-ukrainian.org.ua/dev/
- Click on 'Зареєструватись' Login Item
- Click on 'Відвідувач' Button
- Click on 'Google account' Icon

**Actual result**
An error appears

**Expected result**
User is registered via Google account successfully

**User story and test case links**
User story #97

**Labels to be added**
"Bug", Priority ("high"), Severity ("low"), Type ("Functional")

**Comment by NastiaYonka** [comment]
1. Click on ЗАРЕЄСТРУВАТИСЯ
2. Click on GOOGLE ICON 

Actual result: Whitelabel error page
Expected result: User is registered via Google account successfully
