### ISSUE TITLE
Restoring password

### ISSUE THREAD

**Issue by NazarMedynskyy** [ita-social-projects/TeachUA#577]
As a user, I want to be able to reset my password, so that I can recover or change my password.

Acceptance criteria:

If user wants to change or recover the password, should be chosen the option “Забули пароль?”
![image](https://user-images.githubusercontent.com/86045189/123221136-4aa02b00-d4d7-11eb-8e3a-ea288d89586e.png)

After the option “Забули пароль?” is selected, the next pop-up screen would require entering user’s email and clicking button “Відновити”
![image](https://user-images.githubusercontent.com/86045189/123221234-66a3cc80-d4d7-11eb-93ac-a33c142534a8.png)

“Email” according to the following format: local-part@domain.com

After clicking the button “Відновити” user would see the pop-up screen with system message “Перевірте свій емейл та знайдіть лист із темою «Відновлення паролю»”
![image](https://user-images.githubusercontent.com/86045189/123221305-7d4a2380-d4d7-11eb-8cad-0dd2d9360044.png)

If user should follow the link from the email’s inbox, the system would redirect to the password recovery page
![image](https://user-images.githubusercontent.com/86045189/123226856-b3d66d00-d4dc-11eb-8ce9-f60ca4c98b00.png)
 
User will need to fill the required fields as a “New Password”, “Re-enter New Password” and click the button “Змінити пароль”
Password cannot be shorter than 8 characters and longer than 20 characters. Can contain the following characters: upper/lower-case letters, numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?). 

Symbols entered in the required fields are transformed in asterisks on typing

New Password cannot be same as previously used password

Password criteria “Пароль повинен містити великі/маленькі літери, цифри та спеціальні символи” under the login field “New Password” should be displayed to the user if user did not meet the password requirements 
![image](https://user-images.githubusercontent.com/86045189/123227106-ec764680-d4dc-11eb-83a3-74875fff89af.png)

Validate that inputs in “New Password” and “Re-enter Password” data fields match
If the password entered does not match the criteria specified and user hits “Змінити пароль”, the system shows error alert "Пароль не відповідає критеріям"

After successful validation of all entered password fields and on clicking “Змінити пароль”, the system shows a message indicating successful password reset “Ваш пароль успішно змінений” and route user to Login screen
![image](https://user-images.githubusercontent.com/86045189/123227275-1a5b8b00-d4dd-11eb-90c3-f7d7c622efd8.png)

**Comment by MartaHorbatska** [comment]
Update: Can contain the following **LATIN** characters: upper/lower-case,  numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?) // RUS, UKR letters are not valid

**Comment by muhalenuch** [comment]
Update (2): Can contain the following LATIN characters: upper/lower-case, numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?, №, - , *) // RUS (e.g. 'ы', 'э', 'ё', 'ъ'), UKR (e.g. 'ґ', 'ї' ) letters are not valid
Error message appears: “Пароль повинен містити великі/маленькі літери латинського алфавіту, цифри та спеціальні символи”
