### ISSUE TITLE
Mobile. 'Про нас' page view

### ISSUE THREAD

**Issue by tetianaperv** [ita-social-projects/TeachUA#579]
As a user I want to be able to see the site "Про нас" page in the mobile view so that I could see it from my phone

Mockups:
__Project_: https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A189353_

Acceptance criteria

1. User sees the current state of web page in the mobile view
2. User can scroll down the page, vertical scroll is shown when page is scrolled down-scrolled up

**Comment by mpetliak** [comment]
**BA notes**: 
1) Texts should be stretched across the width of the mobile screen
2) Design bug 
![image](https://user-images.githubusercontent.com/83717595/123386451-5d7e3280-d59f-11eb-8d25-564198f64c93.png)
**Photos should be stretched across the width of the mobile screen** like below:
![image](https://user-images.githubusercontent.com/83717595/123386570-7ab30100-d59f-11eb-8ed1-329693399d18.png)
@marianben kindly take those notes into consideration

**Comment by Natalia96255** [comment]
The same bug #603
