### ISSUE TITLE
Mobile. 'Послуги українською' page view

### ISSUE THREAD

**Issue by tetianaperv** [ita-social-projects/TeachUA#580]
As a user I want to be able to see the site 'Послуги українською' page in the mobile view so that I could navigate to it from my phone

**Description**
Mockups:
_Services_: https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A189353

Acceptance criteria

User sees current state of web page in the mobile view
User can scroll down the page, vertical scroll is shown when page is scrolled down-scrolled up

**Comment by DmytroKarman** [comment]
opened bug 
https://github.com/ita-social-projects/TeachUA/issues/618
