### ISSUE TITLE
Mobile. Registration

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#591]
As a user I want to register on the platform through my mobile, so that I don't need to use my PC

Mockup: Main | Registration https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A189617

**Acceptance criteria**
1. User sees registration pop-up stretched across the width of the display
2. Current web version state as is should be applied, no additional improvements are supposed to be added

**Comment by DmytroKarman** [comment]
opened bugs 
https://github.com/ita-social-projects/TeachUA/issues/617
https://github.com/ita-social-projects/TeachUA/issues/616
