### ISSUE TITLE
Mobile. Advanced search results

### ISSUE THREAD

**Issue by mpetliak** [ita-social-projects/TeachUA#594]
As a user, I want to be able to search clubs on my phone, so that I get search results

Mockup: Club | Grid 
![124449649-5370e680-dd8c-11eb-845e-ba5c594234a0](https://user-images.githubusercontent.com/84569550/126965579-199b9e0a-7cbd-42dc-b16f-5bf97762780e.png)

**Acceptance criteria**
1. When user applies searching filters and confirms - user is redirected to the results page
2. Default sorting order - ASC
3. Sorting criteria from web version are applied
4. There are "chips" with selected categories
5. Only table view is available
6.  'Показати на мапі' button is shown under the page title (assumed location) <- design bug
![124449649-5370e680-dd8c-11eb-845e-ba5c594234a0](https://user-images.githubusercontent.com/84569550/126965712-864e8a32-4aff-4cf7-8e82-b34ff0ff7623.png)

**Comment by DmytroKarman** [comment]
Mockup updated

**Comment by Olha-Pylyp** [comment]
Acceptance criteria update
2.Default sorting order 'Alphabetically'- ASC, 'by rating' - DESC
