### ISSUE TITLE
[Додати локацію] Error message "Некоректна назва локації" disappear when user continues fill in next fields

### ISSUE THREAD

**Issue by Natalia96255** [ita-social-projects/TeachUA#597]
**Environment:** Windows 10 Pro, Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in as admin 'Email'="admin@gmail.com", 'Password'="admin"
3. Click 'Додати центр' button
4. Fill in name in 'Назва' field
5. Click '+Додати локацію' button
6. Fill in 'Назва' field in russian language
7. Continue fill in next fields

**Actual result**
Error message under 'Назва' field disappear, a green tick appears. User can see error message again after clicking 'Додати' button
![location](https://user-images.githubusercontent.com/84569630/124615291-cb6b0980-de7d-11eb-8a2b-2cd76c06a667.png)

**Expected result**
Error message is under 'Назва' field until user will text valid data.

User story #291 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Low"), Type ("Functional").

**Comment by Natalia96255** [comment]
Still the same issue

**Comment by DmytroKarman** [comment]
bug is still present
