### ISSUE TITLE
[Додати гурток, центр, локацію] User cannot navigate by arrows on the keyboard in all fields

### ISSUE THREAD

**Issue by Natalia96255** [ita-social-projects/TeachUA#599]
**Environment:** Windows 10 Pro, Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in as admin 'Email'="admin@gmail.com", 'Password'="admin"
3. Click 'Додати центр' button
4. Fill in name in 'Назва' field
5. Try to navigate by arrows on the keyboard in this field

**Actual result**
The cursor does not move, user can move cursor only by clicking the mouse

**Expected result**
User should be able navigate by keyboard

**Note**
This issue is in all fields in 'Додати гурток', 'Додати центр' and 'Додати локацію' windows

User story #70 #71 #291 

**Labels to be added**
"Bug", Priority ("pri: Medium"), Severity ("severity: Low"), Type ("Functional").

**Comment by DmytroKarman** [comment]
bug is still present

**Comment by yuliiahorak** [comment]
Issue is fixed

https://user-images.githubusercontent.com/82143371/127371213-997736ee-ebd4-4b6c-9700-98d84864a050.mp4
