### ISSUE TITLE
[Mobile. 'Челендж' page view] Wrong alignment of Facebook, Youtube, Instagram icons

### ISSUE THREAD

**Issue by SvitlanaYelisyeyeva** [ita-social-projects/TeachUA#603]
**Environment:** Windows 10, Google Chrome Version 91.0.4472.124 (Official Build) (64-bit).
**Reproducible:** always
**Build found**: last commit 

**Preconditions:**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Choose mobile version 
3. Set screen resolution 320x667 (Responsive)

**Steps to reproduce:**
1. Go to the 'Челендж' page
2. Scroll down to the bottom of the 'Челендж' page

**Actual result**
Wrong alignment of Facebook, Youtube, Instagram icons
![image](https://user-images.githubusercontent.com/84569656/125170891-ee692680-e1b9-11eb-81b5-0a01b210b69d.png)

**Expected result**
![Capture](https://user-images.githubusercontent.com/84569656/125754048-ad78598d-4acc-488f-88ac-fd084a847de6.JPG)

**User story** 
https://github.com/ita-social-projects/TeachUA/issues/588

Labels to be added
Severity "Low"

**Comment by SvitlanaYelisyeyeva** [comment]
Wrong alignment of Facebook, Youtube, Instagram icons is valid also for Moto G4, Galaxy S5, iPhone 5/SE, iPhone 6/7/8, iPhone X, iPad, Surface Duo, Galaxy Fold.

**Comment by Natalia96255** [comment]
Incorrect alignment is present on all pages
