### ISSUE TITLE
[Розширений пошук] UI  wrong alignment of club information when clubs are displays is list 

### ISSUE THREAD

**Issue by DmytroKarman** [ita-social-projects/TeachUA#612]
**Environment:** MacOS Google Chrome 91.0.4472.106..
**Reproducible:** always.
**Build found:** last commit 

**Steps to reproduce**
1. Go to 'https://speak-ukrainian.org.ua/dev/'
2. Click on advanced search icon 
3. Click on list display icon

**Actual result**
all clubs are displays in a list with alignment issue 
<img width="1279" alt="Знімок екрана  о 17 13 42" src="https://user-images.githubusercontent.com/84569550/125305083-c3581180-e336-11eb-8dcc-e6accd4c3264.png">
<img width="1280" alt="Знімок екрана  о 17 14 05" src="https://user-images.githubusercontent.com/84569550/125305195-d5d24b00-e336-11eb-99c9-3ab8460c628f.png">

**Expected result**
text alignment should correspond with figma 
<img width="1280" alt="Знімок екрана  о 17 18 15" src="https://user-images.githubusercontent.com/84569550/125305380-f8fcfa80-e336-11eb-9f02-7be0590d56c3.png">

**User story and test case links**
E.g.: "User story #274 
[Test case](https://jira.softserve.academy/browse/100)"

**Comment by DmytroKarman** [comment]
For center alignment use same logic as for clubs

**Comment by irenepetriv** [comment]
'Centers' names placement does not correspond to mock-up
![Знімок екрана (180)](https://user-images.githubusercontent.com/87877499/129409761-c1dcb747-91d8-4630-b418-fb968cd2cb87.png)
![Uploading 125305380-f8fcfa80-e336-11eb-9f02-7be0590d56c3.png…]()

**Comment by yuliiahorak** [comment]
The bug is still reproducible
![Знімок екрана 2021-08-16 234425](https://user-images.githubusercontent.com/82143371/129627343-c13370d1-29d4-4803-b5be-248f5f6b0fcf.png)

**Comment by yuliiahorak** [comment]
The bug is not reproducible
![Знімок екрана 2021-08-18 194626](https://user-images.githubusercontent.com/82143371/129938911-6583fca3-037e-49a9-a95b-aaefb1f3bdd4.png)
