### ISSUE TITLE
[Mobile. Registration] Missing  UI elements

### ISSUE THREAD

**Issue by DmytroKarman** [ita-social-projects/TeachUA#616]
**Environment:** MacOS Google Chrome 91.0.4472.106..
**Reproducible:** always
**Build found:** last commit f

**Steps to reproduce**
1. Go to 'https://speak-ukrainian.org.ua/dev' open mobile view set  MOTO G4
2. open registration window 

**Actual result**
UI missing buttons 'Відвідувач' and 'Викладач' and registration with Google and Facebook icons 

<img width="300" alt="Знімок екрана  о 12 39 38" src="https://user-images.githubusercontent.com/84569550/125431594-461fc701-2d86-4fe8-85b9-fcd7c393d4bb.png">

**Expected result**
UI should correspond to mockup 
https://www.figma.com/file/d2105v4IAq59MjeB01DfsR/%D0%9D%D0%B0%D0%B2%D1%87%D0%B0%D0%B9-%D1%83%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%81%D1%8C%D0%BA%D0%BE%D1%8E-%7C-Delivery?node-id=1805%3A189617

**User story and test case links**
E.g.: "User story #591

**Comment by softservedata** [comment]
When  you logging by Google you also register with it
