### ISSUE TITLE
[Mobile] Wrong layout of the 'Показати на карті' button

### ISSUE THREAD

**Issue by SvitlanaYelisyeyeva** [ita-social-projects/TeachUA#626]
**Environment:** Windows 10, Google Chrome Version 91.0.4472.124 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit 

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev
2. Choose mobile version

**Steps to reproduce**
1. Set screen resolution 414x736 (iPhone 6/7/8 Plus)
2. Click on the burger menu
3. Select 'Гуртки'
4. Pay attention to the 'Показати на мапі' button

**Actual result**
Wrong layout of the 'Показати на карті' button
![image](https://user-images.githubusercontent.com/84569656/126334724-6840d409-9754-4cca-9494-379c73f8bbe4.png)

**Expected result**
The 'Показати на мапі' button should overlap the city-name-box.

**Labels to be added**
Severity 'Low'

**Comment by SvitlanaYelisyeyeva** [comment]
The same bug is valid for iPad, 
![image](https://user-images.githubusercontent.com/84569656/126338184-067f426c-cc4e-4e24-a38f-24a696e2e427.png)
Surface Duo
![image](https://user-images.githubusercontent.com/84569656/126338522-c1134c89-391d-44cc-b005-869396337a18.png)
Pixel 2, Pixel 2XL, iPhone 6/7/8

**Comment by DmytroKarman** [comment]
bug is still present

**Comment by NataliiaDovha** [comment]
Wrong layout of the 'Показати на карті' button is still present on iPad,
![ipad](https://user-images.githubusercontent.com/87872581/127361625-d6e4bbc7-b8f1-4af5-96da-4da4b1fe1cef.png)
Surface Duo
![surface](https://user-images.githubusercontent.com/87872581/127361764-b739272c-ec22-4df8-bf06-c248d6e51289.png)
