### ISSUE TITLE
[Додати локацію. Додати гурток] The 'Адреса' field should not accept letters of the Russian alphabet 

### ISSUE THREAD

**Issue by SvitlanaYelisyeyeva** [ita-social-projects/TeachUA#628]
**Environment:** Windows 10, Google Chrome Version 91.0.4472.124 (Official Build) (64-bit).
**Reproducible:** always
**Build found:** last commit 

**Preconditions**

1. Go to https://speak-ukrainian.org.ua/dev
2. Log in as an Administrator ('Email'="admin@gmail.com", 'Password'="admin")
3. Go to the User's private office
4. Click the ‘Додати гурток’ in the drop-down list.
5. Fill in all the mandatory fields of the 'Основна інформація' tab
6. Click the 'Наступний крок' button
7. Click the 'Додати локацію' link on 'Контакти' tab

**Steps to reproduce**
1. Enter 'быстро' into the 'Адреса' field
2. Fill all the other fields with valid data.
3. Click the 'Додати' button 

**Actual result**
Data with letters of the Russian alphabet is accepted into the 'Адреса' field
![Screenshot (112)](https://user-images.githubusercontent.com/84569656/126737106-d26945c5-1b21-4b16-bf67-8b5ac20cc8d8.png)
![Screenshot (113)](https://user-images.githubusercontent.com/84569656/126737109-da99b0b4-b2d8-4038-b138-3cc10dca68f5.png)

**Expected result**
The 'Адреса' field should not accept letters of the Russian alphabet 

**User story**
https://github.com/ita-social-projects/TeachUA/issues/291

**Comment by DmytroKarman** [comment]
bug is still present 
<img width="1268" alt="Знімок екрана  о 15 48 23" src="https://user-images.githubusercontent.com/84569550/127324822-89c19416-ef86-4d1c-868c-70ff04fe29ed.png">

**Comment by IuliiaKrivenkova** [comment]
The 'Адреса' field does not accept letters of the Russian alphabet
