### ISSUE TITLE
['Челендж' page] The title of the banner does not follow its place when changing resolution

### ISSUE THREAD

**Issue by SvitlanaYelisyeyeva** [ita-social-projects/TeachUA#629]
**Environment:** Windows 10, Google Chrome Version 91.0.4472.124 (Official Build) (64-bit).
**Reproducible:** always.
**Build found:** last commit 

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev

**Steps to reproduce**
1. Go to the 'Челендж' page
2. Change the resolution from 1200x721px to 821x721px
3. Pay attention to the title of the banner place

**Actual result**

https://user-images.githubusercontent.com/84569656/126790633-4a137a04-b1fb-4d8d-89b0-1e9515aa4164.mp4

**Expected result**
The title should remain centered on the banner.

Severity Low

**Comment by irenepetriv** [comment]
Bug appears at resolution 676x783

https://user-images.githubusercontent.com/87877499/127365415-041187b8-808a-41f8-be51-702e0d8c0a7e.mp4

**Comment by NataliiaDovha** [comment]
The same bug still appears at the resolution from 902x657px to 910x657px.

https://user-images.githubusercontent.com/87872581/128157287-6f598299-8a34-45a9-ad8d-3025154a8d92.mp4
