### ISSUE TITLE
[Поле пошуку] Input text covers the search icon and cross icon

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#633]
**Environment:** Windows 10 Pro., Google Chrome
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
Open website on a home page https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to 'Поле пошуку'
2. Enter Програмування, робототехніка, STEM 

**Actual result**
Input text covers the search icon and cross icon

![Search field](https://user-images.githubusercontent.com/87894920/127135097-3e6cf48d-7810-44f1-88e6-6417b0290854.png)

**Expected result**
Input text should not cover the search icon and cross icon

![Search field 2](https://user-images.githubusercontent.com/87894920/127135666-c56baec5-6677-40ed-9549-b07081174b6f.png)

**User story and test case links**
User story #77

**Comment by DmytroKarman** [comment]
for display resolution 2560 x 1600 bug is still present 
<img width="1280" alt="Знімок екрана  о 16 00 36" src="https://user-images.githubusercontent.com/84569550/127327659-622efa62-f454-41b0-8f6d-95ee80ff3c9f.png">

**Comment by IuliiaKrivenkova** [comment]
Input text does not cover the search icon
