### ISSUE TITLE
[Залишити коментар] Allignment of elements on Comment page

### ISSUE THREAD

**Issue by MartaHorbatska** [ita-social-projects/TeachUA#640]
**Environment:**Windows 10, Google Chrome Версия 92.0.4515.107 (Официальная сборка), (64 бит) 
**Reproducible:** always 
**Build found:** last commit 
 
**Preconditions**
Log in with credentials
- admin@gmail.com
- admin

**Steps to reproduce**

1. Go to 'Гуртки'
2. Click on button 'Детальніше'  // detailed information about  one of them. 
3. Click on 'Залишити коментар'
4. Click on 'Скарга'
 
**Actual result**
 Button 'Надіслати'  in the comment page - tab 'Скарга' is downshifted. 
 
![скарга alignment](https://user-images.githubusercontent.com/87965983/127304584-dff3ae19-aadc-478e-9d97-140a1632d722.png)

**Expected result**
 Button 'Надіслати' must be aligned on the same level as the Button 'Надіслати' on the tab 'Коментар'
 
 
![коментар](https://user-images.githubusercontent.com/87965983/127305811-9c0ae1f3-9819-482d-b5cf-2589d1c6b5cf.png)
![скарга alignment](https://user-images.githubusercontent.com/87965983/127305812-ace56695-fb96-4552-8269-bc2e57af73ed.png)

User story and test case links
User story #115

**Comment by RostyslavNovoselskyi** [comment]
There is additional field "Оцінка" in the Коментар tab so that, both buttons can not be aligned on the same level.
