### ISSUE TITLE
[Додати локацію.Додати гурток] Wrong error message when ‘Телефон’ field contains letters or special characters

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#646]
**Environment:** Windows 10, Google Chrome 92.0.4515.107 (Розробка) (64-розрядна версія)
**Reproducible:** always
**Build found:** last commit 

Preconditions
The user should be logged in the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce

Click on 'Додати гурток' button on the main page or in user's private office
Fill in all the mandatory fields of the 'Основна інформація' tab
Click the 'Наступний крок' button
Click the 'Додати локацію' button
Enter in "Номер телефону" field letters
**OR** Enter in "Номер телефону" field special characters

**Actual result**
The wrong error message appears "Телефон не відповідає вказаному формату"
![Літери в тел](https://user-images.githubusercontent.com/82143371/127361399-b365cb0a-5555-43d7-bb46-5d0fdd5f0062.png)
![спец символи](https://user-images.githubusercontent.com/82143371/127361422-2fdde58d-dd26-4a96-9b77-fda0a65d38c5.png)

**Expected result**
‘‘Телефон не може містити літери’’ error message should appear after "Номер телефону" field
‘‘Телефон не може містити спеціальні символи’’ error message should appear after "Номер телефону" field

**User story and test case links**
 #291

**Comment by yuliiahorak** [comment]
When in "Телефон" field is entered 9 symbols (///593585) , error messages are shown: "Телефон не відповідає вказаному формату" and "Телефон не може містити спеціальні символи". The only 1 message shoud be printed: "Телефон не може містити спеціальні символи"
![2](https://user-images.githubusercontent.com/82143371/129621808-d31e926e-b109-45a1-8730-057aaafc3af2.png)

When in "Телефон" field is entered 9 symbols (qwe593585) , error messages are shown: "Телефон не відповідає вказаному формату" and "Телефон не може містити літери". The only 1 message shoud be printed: "Телефон не може містити літери"
![1](https://user-images.githubusercontent.com/82143371/129621838-f0080c5e-0c87-47e8-aca6-a8fa0ae87279.png)

**Comment by yuliiahorak** [comment]
The bug is still reproducible
![Додати гурток символи](https://user-images.githubusercontent.com/82143371/133238427-b55ae0c1-ac4e-43a0-a301-2258a3070c4f.png)
![Додати гурток літери](https://user-images.githubusercontent.com/82143371/133238431-2ee0059b-6d62-4b35-ae76-fcd93fdbb3ab.png)

**Comment by AndriyKolodiy** [comment]
according to the agreements with the product owners(Ihor & Yaroslav), it was decided to display only one error message "Телефон не відповідає вказаному формату" and display other messages as additional information in the tooltip
