### ISSUE TITLE
[Редагування профілю] Dynamic validation of password field does not work

### ISSUE THREAD

**Issue by NataliiaDovha** [ita-social-projects/TeachUA#649]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in

**Steps to reproduce**
1. Go to 'Мій Профіль' page
2. Click on 'Редагувати профіль'
3. Click on chechbox with the label 'Змінити пароль'
4. In the 'Введіть новий пароль' field enter 123456789
5. In the 'Підтвердіть новий пароль' field enter 123456789
6. Remove from the 'Введіть новий пароль' field number 9

**Actual result**
The error message 'Значення поля ‘Підтвердити пароль’ має бути еквівалентним значенню поля ‘Пароль’' does not appear.
https://user-images.githubusercontent.com/87872581/127385809-c980f86a-ed0b-4fda-9dd4-bee6e8b0a9e3.mp4

**Expected result**
Validation should track changes in both fields and error message 'Значення поля ‘Підтвердити пароль’ має бути еквівалентним значенню поля ‘Пароль’' should appear.
![password](https://user-images.githubusercontent.com/87872581/127386005-762c5dee-b50a-4c07-aea8-4e184dc73380.png)

**User story link**
User story #164

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
