### ISSUE TITLE
[Поле пошуку] It is possible to fill in only 3 letters in search field

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#650]
**Environment:** Windows 10 Pro., Google Chrome
**Reproducible:** always
**Build found:** last commit

**Preconditions**
Open website on a home page https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Go to 'Поле пошуку'
2. Start to fill in more than 3 letters

**Actual result**

It is impossible to fill in more than 3 letters in the search field

![search 3](https://user-images.githubusercontent.com/87894920/127387568-c7504e7c-7ee6-4012-9132-114200311a84.png)

**Expected result**
 It is possible to fill in more than 3 letters in the search field

**User story and test case links**
E.g.: "User story #77

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
