### ISSUE TITLE
[Додати локацію] 'Додати' button is enabled when mandatory fields aren't filled//creating new Club or Center, after changing field City

### ISSUE THREAD

**Issue by MartaHorbatska** [ita-social-projects/TeachUA#659]
**Environment:** Windows 10, Версия 92.0.4515.107 (Официальная сборка), (64 бит)
**Reproducible:** always (when adding Location creating Center or creating Club)
**Build found:** last commit

**Steps to reproduce:**
1. Go to 'https://speak-ukrainian.org.ua/dev/'
2. Log in as admin 'Email'="admin@gmail.com", 'Password'="admin"
3. Click 'Додати гурток' button
4. Fill in all fields to 'Контакти' step 
5. Go to 'Додати локацію', fill in all fields.
6. Change city to another One.

**Actual result**
'Додати' button is enabled when mandatory fields are empty.
 
![button Додати](https://user-images.githubusercontent.com/87965983/127479092-3c55d07f-aa6d-4e53-827c-3d9cceff6c4e.png)

**Expected result**
 'Додати' button  must be disabled when mandatory  fields are not filled.
 
 User story #291  
‘Додати’ button becomes active only after all mandatory fields are filled.

![button Додати](https://user-images.githubusercontent.com/87965983/127480704-b6843d1a-db70-4a8f-b25a-7ddc54976343.png)

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by MartaHorbatska** [comment]
Button 'Додати' is active,  when mandatory fields are not filled.

**Comment by MartaHorbatska** [comment]
Actual result: Button 'Додати' is active, when mandatory fields are not filled.
Steps to reproduce:
  - 'Додати локацію', fill in all fields.
  - Change city to another One> entered data from  address and coordinates is deleted  and button is active.

![button](https://user-images.githubusercontent.com/87965983/129665317-d2d343ab-6547-4bdb-bb72-9d3c7f909efa.png)

**Comment by AnastasiiaKukh** [comment]
Bug is closed
