### ISSUE TITLE
[Mobile version.Мій профіль] Wrong alignment of elements in My profile UI 

### ISSUE THREAD

**Issue by MartaHorbatska** [ita-social-projects/TeachUA#683]
**Environment:** Windows 10, Версия 92.0.4515.107 (Официальная сборка), (64 бит), Iphone X
**Reproducible:** always
**Build found:** last commit

**Preconditions**
Open mobile version of site.
Go to https://speak-ukrainian.org.ua/dev/
Log in as admin 'Email'="admin@gmail.com", 'Password'="admin"
Click 'My profile'  

**Steps to reproduce**

**Actual result**
UI does not match to mock-up
Wrong alignment of elements
![my profile UI](https://user-images.githubusercontent.com/87965983/128315038-5f4f9d6d-6da0-405d-8bb6-389d39f4f5ac.png)

**Expected result**

![mock up profile](https://user-images.githubusercontent.com/87965983/128315006-2214867c-dd24-4d8c-9187-b6c944e63cf4.png)

User story #674

**Comment by MartaHorbatska** [comment]
**Actual result**
UI does not match to mock-up
Wrong alignment of elements

![My profile](https://user-images.githubusercontent.com/87965983/129415443-a28fb225-7c29-44b6-9e27-a31429b484df.png)

**Comment by MartaHorbatska** [comment]
Actual result
Wrong alignment of elements. 

- Layout of the menu list  goes  beyond the page. 
![image](https://user-images.githubusercontent.com/87965983/134116755-48b94dc8-2e54-4ef4-972a-a8b3ff15fe84.png)

- Layout of the centers blocks goes beyond the page. 
![image](https://user-images.githubusercontent.com/87965983/134116817-076724bb-8f71-427a-a2ad-beeb36478c39.png)

**Comment by RomanSahan** [comment]
The bug is not fixed on version IPhone 5/SE.
![inc alignment](https://user-images.githubusercontent.com/80393478/135866406-51e3583c-7b6c-46c4-8da0-6085b4d62cc6.png)

Furthermore, the alignment and background colour of 'Гуртки/центри' dropdown list is not correct
![inc align2](https://user-images.githubusercontent.com/80393478/135866918-11591079-adbc-4937-87fb-f3f356d812bb.png)
