### ISSUE TITLE
Додати гурток

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#70]
As ‘Керівник’ of a club, I want to add my club on the website, so that an added club will be present on the website.

**Description:**

There are three ways to open ‘Додати гурток’ pop-up:
1. Go to user’s private office, click on ‘+Додати’ button, then choose ‘Додати гурток’ in the drop-down list
2. After clicking ‘Додати новий гурток’ button on the ‘Додати центр’ pop-up
3. After clicking 'Додати гурток' button on the right upper corner of the header on any page

**‘Додати гурток’ pop-up consists of 3 steps with the next parameters:**
 
| Step  | Parameters |
| ------------- | ------------- |
| 1 step- **‘Основна інформація’**  | ‘Назва *’ (mandatory), ‘Категорія *’ (mandatory), ‘Вік *’ (mandatory), ‘Приналежність до центру’.
| 2 step- **‘Контакти’**  | If **‘Додати гурток’ pop-up** was opened after clicking **‘Додати новий гурток’ button** on the **‘Додати центр’ pop-up** OR If **‘Додати гурток’ pop-up** was opened after clicking **‘Додати гурток’ in user’s private office** / after clicking **'Додати гурток' button on the header** and ‘**Приналежність до центру’ is chosen**, then there is: 1) **a checkbox list with locations** of that center (all location are checked by default). 2) **a checkbox ‘Доступний онлайн’** (optional, but must be checked automatically if all locations are unchecked). 3) ‘Телефон *’(mandatory), ‘Facebook’, ‘WhatsApp’, ‘Email’, ‘Skype’, ‘Telegram’, ‘Viber’, ‘Instagram’. |
|  | If **‘Додати гурток’ pop-up** was opened after clicking **‘Додати гурток’ in user’s private office** / after clicking **'Додати гурток' button on the header**  and **‘Приналежність до центру’ isn’t chosen**, then there is: 1) **a button ‘+ Додати локацію’** (#291 ). After clicking it, ‘Додати локацію’ pop-up is opened. After filling all mandatory fields on the ‘Додати локацію’ pop-up and clicking ‘Додати’ button, the location is added. Min 0 and max 50 locations can be added. 2) **a checkbox ‘Доступний онлайн’** (optional, but must be checked automatically if no location is added). 3) ‘Телефон *’ (mandatory), ‘Facebook’, ‘WhatsApp’, ‘Email’, ‘Skype’, ‘Telegram’, ‘Viber’, ‘Instagram’.
|3 step- **‘Опис’**| ‘Опис *’ (mandatory), ‘Лого’, ‘Фото’.|

**Parameters specifications:**

| Parameter  | Specifications |
| ------------- | ------------- |
| ‘Назва’ | 1. Languages: Ukrainian, English. |
| | 2. Can contain letters, numbers and reserved characters (()/[]!"#$%&'*+\n, ,-.:\r;<=>?|@№_`{}~^)
|  | 3. Min: 5 characters, Max: 100 characters.|
| ‘Вік’  | From n to m; m - optional; 1-6,12-16, 6+, 18+.|
| ‘Приналежність до центру’  | If ‘Додати гурток’ pop-up was opened after clicking ‘Додати гурток’ button on the ‘Додати центр’ pop-up, then selector ‘Приналежність до центру’ automatically takes the name of that center.  If not, then there is a dropdown list with all centers that were created by the current user.|
| ‘Телефон’ | Format:  input mask '+38(___) ___ __ __'  |
|‘Email’  | Format: local-part@domain.com |
| ‘Опис’ | 1. Languages: Ukrainian, English.|
|  | 2. Can contain letters, numbers and reserved characters (!"#$%&'()*+,-./:;<=>?@[\]^_`{}~). |
|  | 3. Min: 40 characters, Max: 1500 characters.|
| ‘Лого’ | 1. If ‘Лого’ isn’t added, then the icon of the main category is set by default.|
| ‘Обкладинка’ | 1. Only one photo can be added in ‘Photo’ and this photo will be the main photo for a club page.|
|  | 2. The name of an added photo is clickable and allows to change a photo to another.|
| ‘Галерея’ | 1. ***HOW MANY PHOTOS CAN BE UPLOADED, WHAT FORMAT AND SIZE* ???** |
|  | 2. The name of an added photo is clickable and allows to change a photo to another.|

Fields validation:
| Reason  | Error messages |
| ------------- | ------------- |
| If value of ‘Назва’ parameter contains forbidden characters| ‘Це поле може містити тільки українські та англійські літери, цифри та спеціальні символи’|
| If value of ‘Опис’ parameter contains forbidden characters | ‘Це поле може містити тільки українські та англійські літери, цифри та спеціальні символи’  |
|If ‘Назва’ parameter contains less than 5 characters  | ‘Назва гуртка закоротка’  |
| If ‘Назва’ parameter contains more than 100 characters | ‘Назва гуртка задовга’  |
| If ‘Опис’ parameter contains less than 40 characters  | ‘Опис гуртка закороткий’ |
| If ‘Опис’ parameter contains more than 1500 characters | ‘Опис гуртка задовгий’  |
| If the value of ‘Email’ doesn’t match the ‘local-part@domain.com’  format| Некоректний формат Email’  |
| If  value of ‘Телефон’ textbox contains reserved characters , except ‘+’ as the first character  | ‘Телефон не може містити спеціальні символи’|
|If  value of ‘Телефон’ textbox contains letters  |  ‘Телефон не може містити літери’ |
|If the value of ‘Телефон’ textbox contains less than 10 symbols  |  ‘Телефон не відповідає вказаному   формату’|
|If the amount of locations is more than 50|'Дозволена кількість доданих локацій - 50'|

**Buttons Specifications:**
|  Button | Specification|
| ------------- | ------------- |
| ‘Наступний крок’ button  | The button becomes active only when all mandatory fields are filled  |
| ‘Назад’ button  | The button returns a user to the previous step|

**AC:**
1.	A user can add a club with all mentioned parameters
2.	It’s impossible to add a club without filling in all mandatory fields
3.	It’s possible to add a club without filling in optional fields
4.	All info about the added club can be found in the database and on the website

The frame on Figma: 464

If ‘Додати гурток’ pop-up was opened after clicking ‘Додати гурток’ button on the ‘Додати центр’ pop-up OR If ‘Додати гурток’ pop-up was opened after clicking ‘+Додати’ and choosing ‘Додати гурток’ in user’s private office and ‘Приналежність до центру’ is chosen:

![image](https://user-images.githubusercontent.com/78953350/112151028-6bf82f00-8be9-11eb-9328-bd17b3c0b0ef.png)
![image](https://user-images.githubusercontent.com/78953350/112160894-48d27d00-8bf3-11eb-8ff3-6d9bc111ec9b.png)
![02](https://user-images.githubusercontent.com/83238027/120610615-08497800-c45c-11eb-87df-02cad08e4142.png)

If ‘Додати гурток’ pop-up was opened after clicking ‘+Додати’ and choosing ‘Додати гурток’ in user’s private office and ‘Приналежність до центру’ isn’t chosen:
![image](https://user-images.githubusercontent.com/78953350/112151242-acf04380-8be9-11eb-9df9-f22ff97f2959.png)
![image](https://user-images.githubusercontent.com/78953350/112151262-b24d8e00-8be9-11eb-9217-9db98aa9a825.png)
![02](https://user-images.githubusercontent.com/83238027/120610598-041d5a80-c45c-11eb-8ae1-cf60c488c2d9.png)

**Comment by softservedata** [comment]
1. Backend is done
2. Frontend in progress

**Comment by mpetliak** [comment]
Додати гурток button was made by design, there is no design bug or contradictionі in the logic, thus current behavior can be considered as the correct one

**Comment by Natalia96255** [comment]
Wrong error message in 'Опис гуртка' field
