### ISSUE TITLE
Додати центр

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#71]
As ‘Керівник’, I want to create a center of my clubs

**Description:**
‘Додати центр’ pop-up can be opened from a private office of ‘Керівник’ by clicking ‘+Додати’ button and choosing ‘Додати центр’ in the drop-down list.

 **‘Додати центр’ pop-up contains 4 steps:** 

| Step  | Parameters |
| ------------- | ------------- |
| 1 step - **‘Основна інформація’**  | ‘Назва *’(mandatory), a checkbox list with locations (which were added by ‘Керівник’ to clubs without center that were created previously) and ‘+ Додати локацію’ button. After clicking ‘+ Додати локацію’ button ‘Додати локацію’ pop-up appears (#291 ).  After filling all mandatory fields on the ‘Додати локацію’ pop-up and clicking ‘Додати’ button, the location is added to a checkbox list. |
| 2 step - **‘Контакти’**  | ‘Телефон *’(mandatory), ‘Email’, ‘Facebook’, ‘WhatsApp’, ‘Viber’, ‘Telegram’, ‘Instagram’, ‘Skype’ parameters.|
|3 step - **‘Опис’**| ‘Опис *’ (mandatory), ‘Лого’, ‘Фото’.|
|4 step - **‘Гуртки’** |There is a checkbox with: those clubs which were created by ‘Керівник’ before (don’t refer to other centers yet) and those which were created after clicking ‘+ Додати новий гурток’ button. After clicking on ‘+ Додати новий гурток’ button, ‘Додати гурток’ pop-up appears (#70). The Center should have MIN 1 club. |

**Parameters specifications:**

| Parameter  | Specifications |
| ------------- | ------------- |
| ‘Назва’ | 1. Languages: Ukrainian, English. |
| | 2. Can contain letters, numbers and reserved characters (!"#$%&'()*+,-./:;<=>?@[\]^_`{}~).|
|  | 3. Min: 5 characters, Max: 100 characters.|
| ‘Телефон’ | Format: +38(___) ___ __ __ |
|‘Email’  | Format: local-part@domain.com |
| ‘Опис’ | 1. Languages: Ukrainian, English.|
|  | 2. Can contain letters, numbers and reserved characters (!"#$%&'()*+,-./:;<=>?@[\]^_`{}~).|
|  | 3. Min: 40 characters, Max: 1500 characters.|
| ‘Фото’ |1. Only one photo can be added in ‘Photo’ and this photo will be the main photo for a page of a center. |
|| 2. The name of an added photo is clickable and allows to change a photo to another.|

**Fields validation:**
| Reason  | Error messages |
| ------------- | ------------- |
| If value of ‘Назва’ parameter contains forbidden characters| ‘Це поле може містити тільки українські та англійські літери, цифри та спеціальні символи’|
| If value of ‘Опис’ parameter contains forbidden characters | ‘Це поле може містити тільки українські та англійські літери, цифри та спеціальні символи’  |
|If ‘Назва’ parameter contains less than 5 characters  | ‘Назва центру закоротка’  |
| If ‘Назва’ parameter contains more than 100 characters | ‘Назва центру задовга’  |
| If ‘Опис’ parameter contains less than 40 characters  | ‘Опис центру закороткий’ |
| If ‘Опис’ parameter contains more than 1500 characters | ‘Опис центру задовгий’  |
| If the value of ‘Email’ doesn’t match the ‘local-part@domain.com’  format| Некоректний формат Email’  |
| If  value of ‘Телефон’ textbox contains reserved characters , except ‘+’ as the first character  | ‘Телефон не може містити спеціальні символи’|
|If  value of ‘Телефон’ textbox contains letters  |  ‘Телефон не може містити літери’ |
|If the value of ‘Телефон’ textbox contains less than 10 symbols  |  ‘Телефон не відповідає вказаному   формату’|

**Buttons specifications:**
|  Button | Specification|
| ------------- | ------------- |
| ‘Наступний крок’ button  | The button becomes active only when all mandatory fields are filled  |
| ‘Назад’ button  | The button returns a user to the previous step|

AC:
-	‘Керівник’ can add a center after filling all mandatory fields
-	‘Керівник’ can add to the center those clubs which were created before by him/her and which don’t refer to other centers
-	‘Керівник’ cannot add a center without choosing at least one location and at least one club
-	‘Керівник’ can add a center without filling optional fields

![image](https://user-images.githubusercontent.com/78953350/112437892-20ac6080-8d50-11eb-9ede-c185f178c598.png)
![image](https://user-images.githubusercontent.com/78953350/112157656-1bd09b00-8bf0-11eb-944b-3caec51a3559.png)
![image](https://user-images.githubusercontent.com/78953350/112157680-2428d600-8bf0-11eb-8ffe-d823b1a70393.png)
![image](https://user-images.githubusercontent.com/78953350/112157705-2ab74d80-8bf0-11eb-82ba-012bbf543070.png)

**Comment by softservedata** [comment]
1. Backend is done
2. Frontend in progress

**Comment by AnastasiiaKukh** [comment]
Update:

‘Пароль’ must contain the following LATIN characters: upper/lower-case, numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?) // RUS, UKR letters are not valid.

Error message appears: “Пароль повинен містити великі/маленькі літери латинського алфавіту, цифри та спеціальні символи”
