### ISSUE TITLE
[Гуртки] Incorrect number of reviews for the clubs

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#712]
Environment: Windows 10, Google Chrome 92.0.4515.107
Reproducible: always
Build found: the last commit

Preconditions
The user should be logged in the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce

1. Click on "Гуртки" button
2. Click on "Відеоблогінг IT-stat" club, in the right corner of the club

**Actual result**
There are shown three reviews for a club. 
P.S. ( But when the user clicks on "Детальніше" there is no one review for a club.)
![Incorrect review numbers](https://user-images.githubusercontent.com/82143371/129190138-25aaea7e-7f1c-4af7-a9a8-534bd4f22992.png)

**Expected result**
There is no one review for a club.
![No reviews](https://user-images.githubusercontent.com/82143371/129190162-e95b70a2-6ca0-4b3f-a78d-fa8d94dd270c.png)

**User story and test case links**
 "User story #

**Comment by KostiantynStarynets** [comment]
Windows 11 Enterprise, Google Chrome 108.0.5359.125 (64), notebook.
Comments are displayed. 
![Знімок екрана 2023-01-08 224238](https://user-images.githubusercontent.com/117648097/211218210-5d64e529-d0c4-4c64-b883-e2c9972fc16a.jpg)
