### ISSUE TITLE
[Mobile version. Пошук] 'Clear' button is not functioning

### ISSUE THREAD

**Issue by irenepetriv** [ita-social-projects/TeachUA#717]
**Environment:** iPhone 6, iOS 12.5.4, , browser: Chrome
**Reproducible:** always (iPhone 6, iOS 12.5.4), sometimes (iPhone 10xs)
**Build found:** last commit 

**Preconditions**
Go to  https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Tap 'Search' field
2. Enter 'Танці' in 'Search' field
2. Tap 'Clear' button 

**Actual result**
'Clear' button doesn't work using iPhone 6.
'Clear' button works from 3rd attempt using iPhone 10xs.

https://user-images.githubusercontent.com/87877499/129405271-114c3a5e-3b7b-43bf-b673-6c701da1e04d.MP4

**Expected result**
'Clear' button is functioning instantly.

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
