### ISSUE TITLE
[Restoring password] User cannot restore his password using correct values

### ISSUE THREAD

**Issue by irenepetriv** [ita-social-projects/TeachUA#719]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
 Go to https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**

1. Click on 'Увійти'
2. Click on 'Забули пароль?' on 'Вхід' pop-up
3. Enter irene.petriv@gmail.com on 'Відновлення' pop-up
4. Click on 'Відновити'
5. Follow link 'Змінити пароль' in your email
6. Enter correct values in 'Відновлення паролю' pop-up - "Kvitka1989@"

**Actual result**
Error message 'Пароль не відповідає критеріям' appears. User cannot restore his password
![Знімок екрана (190)](https://user-images.githubusercontent.com/87877499/129416158-19884ff9-c26e-4dfc-88cd-2e8522ef62e4.png)

**Expected result**
User restores his password

**User story and test case links**
E.g.: "User story #577

**Comment by ioleh-bleep-bloop** [comment]
Bug is reproducible
![restoring](https://user-images.githubusercontent.com/52464559/132527016-a0ee85a7-2c68-40a3-bda0-abc63da68916.png)
