### ISSUE TITLE
[Restoring password] Incorrect error message 'Пароль не відповідає критеріям' appears upon entering incorrect password values

### ISSUE THREAD

**Issue by irenepetriv** [ita-social-projects/TeachUA#721]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.131 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
Go to https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**

1. Click on 'Увійти'
2. Click on 'Забули пароль?' on 'Вхід' pop-up
3. Enter irene.petriv@gmail.com on 'Відновлення' pop-up
4. Click on 'Відновити'
5. Follow link 'Змінити пароль' in your email
6. Enter incorrect values in 'Відновлення паролю' pop-up - "12345678"

**Actual result**
Incorrect error message 'Пароль не відповідає критеріям' appears for incorrect password complexity and incorrect values are verified.
![Знімок екрана (192)](https://user-images.githubusercontent.com/87877499/129417881-ac1434e0-cc16-423c-a2e0-534757de0da9.png)

**Expected result**
Error message 'Пароль повинен містити великі/маленькі літери, цифри таспеціальні символи' appears below 'Password' field
![Знімок екрана (193)](https://user-images.githubusercontent.com/87877499/129418810-1feb5491-7d7f-4ba4-a902-57dfecc24038.png)

**User story and test case links**
E.g.: "User story #577

**Comment by AnastasiiaKukh** [comment]
Baga is reproduced again
Steps to reproduce

1. Click on 'Увійти'
2.  Click on 'Забули пароль?' on 'Вхід' pop-up
3. Enter kukharska98@gmail.com on 'Відновлення' pop-up
4. Click on 'Відновити'
5. Follow link 'Змінити пароль' in your email
6. Enter  **correct**  values in 'Відновлення паролю' pop-up - "Nastia11!"

Actual result
An error message 'Пароль не відповідає критеріям' appears for correct password.

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
