### ISSUE TITLE
[Додати локацію.Додати центр] Wrong error message when ‘Телефон’ field contains letters or special characters

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#724]
Environment: Windows 10, Google Chrome 92.0.4515.107 (Розробка) (64-розрядна версія)
Reproducible: always
Build found: last commit

Preconditions
The user should be logged in the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce

1. Click on 'Додати центр' button on the main page or in user's private office
2. Fill in all the mandatory fields of the 'Основна інформація' tab
4. Click the 'Додати локацію' button
5. Enter in "Номер телефону" field letters
6. **OR** Enter in "Номер телефону" field special characters

**Actual result**
The wrong error message appears "Телефон не відповідає вказаному формату"
![ntk2](https://user-images.githubusercontent.com/82143371/129421274-8628953f-1e31-4fde-8c17-8d411f826ea2.png)
![тел1](https://user-images.githubusercontent.com/82143371/129421276-8b4cdcc6-42ca-4249-b61b-513c915a5c1e.png)

Expected result
‘‘Телефон не може містити літери’’ error message should appear under "Номер телефону" field
‘‘Телефон не може містити спеціальні символи’’ error message should appear under "Номер телефону" field

**User story and test case links**
 "User story #71

**Comment by yuliiahorak** [comment]
When in "Телефон" field is entered 10 symbols (56888888/) , error messages are shown:  "Телефон не відповідає вказаному формату" and "Телефон не може містити спеціальні символи". The  only 1 message shoud be printed: "Телефон не може містити спеціальні символи"
![Incorrect error](https://user-images.githubusercontent.com/82143371/129619816-a4de0abc-5337-4440-a8ad-e36663c8e7d4.png)

When in "Телефон" field is entered 10 symbols (568888kkk) , error messages are shown:  "Телефон не відповідає вказаному формату" and "Телефон не може містити літери". The  only 1 message shoud be printed: "Телефон не може містити літери"
![Incorrect error2](https://user-images.githubusercontent.com/82143371/129619819-85ed4719-4f1e-4546-b5e9-a788871c3c03.png)

**Comment by yuliiahorak** [comment]
The bug is still reproducible
![спец символи](https://user-images.githubusercontent.com/82143371/133237568-9296205d-3576-4f2a-b42c-77318e366ca3.png)
![літери](https://user-images.githubusercontent.com/82143371/133237572-223d7cf3-db89-4677-9152-d24e799ab416.png)

**Comment by AndriyKolodiy** [comment]
according to the agreements with the product owners(Ihor & Yaroslav), it was decided to display only one error message "Телефон не відповідає вказаному формату" and display other messages as additional information in the tooltip
