### ISSUE TITLE
[Додати гурток] Logged in user via Google cannot add a club

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#741]
**Environment:** Windows 10, Google Chrome version 92.0.4515.107
**Reproducible:** always
**Build found:** last commit

**Preconditions**
Go to https://speak-ukrainian.org.ua/dev
Log in with Google account

**Steps to reproduce**
1. Go to 'Додати гурток' button
2. Fill in all mandatory fields on 'Основна Інформація' tab
3. Click 'Наступний крок'
4. Fill in 'Контакти' field
5. Click on 'Наступний крок'
6. Fill in the 'Опис' field
7. Click on 'Завершити'

**Actual result**
A new club is not added

https://user-images.githubusercontent.com/87877499/129951835-fabced6a-7d14-4cf0-829a-73535820fc7c.mp4

**Expected result**
A new club is added

**User story and test case links**
"User story #70

**Comment by marianben** [comment]
User can`t register when log with Google
