### ISSUE TITLE
[Розширений пошук] Incorrect "За рейтингом" search result is sorted in descending order

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#747]
Environment: Windows 10, Google Chrome 92.0.4515.107 (Розробка) (64-розрядна версія)
Reproducible: always
Build found: the last commit

Preconditions:
The user should be logged in to the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce
1.Go to 'Розширений пошук' button
2.Click on 'Розширений пошук' button
3.On the left side of the page find the parameters for advanced search
4. In the "Місто" drop-down list box remove the selected city
5. Top in the middle of the page click on "За рейтингом" and descending button

**Actual result**
The "За рейтингом" search result is sorted not in descending order

https://user-images.githubusercontent.com/82143371/130039676-26ac8e65-f110-46d2-8915-384ef39db84f.mp4

**Expected result**
The "За рейтингом" search result is sorted in descending order

User story and test case links
 "User story #274

**Comment by KostiantynStarynets** [comment]
Everything works correctly
Windows 11 Enterprise, Google Chrome 108.0.5359.125 (64), notebook.
![Знімок екрана 2023-01-09 223157](https://user-images.githubusercontent.com/117648097/211403187-eb1982ea-e3ea-43a3-9750-9d78acc744b1.jpg)
![Знімок екрана 2023-01-09 223222](https://user-images.githubusercontent.com/117648097/211403189-ac981949-39d6-45de-bb01-2804d1948806.jpg)
