### ISSUE TITLE
[Mobile. Challenge] Links are displayed not in full size

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#759]
Environment: Windows 10, Google Chrome 92.0.4515.107 (Розробка) (64-розрядна версія)
Reproducible: always
Build found: the last commit

Preconditions
The user should be logged in  the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce:
Go to burger menu >'Челендж' >'Мовомаратон'
2.Go to 'Мовомаратон' page: 'Крок4', 'Крок7' 
3.Review the Link 

Actual result
The links are displayed not in full size
![12345](https://user-images.githubusercontent.com/82143371/130826761-c77fc39f-225b-48fe-ba45-4c5b927b14d4.png)
![1234](https://user-images.githubusercontent.com/82143371/130826767-44e4aa8d-2f46-41d4-b131-cb078be1a31e.png)

**Expected result**
The links are displayed in full size
![Знімок екрана 2021-08-25 191538](https://user-images.githubusercontent.com/82143371/130827539-7366b428-3e1e-4c40-a12d-e721bc4e1108.png)
![Знімок екрана 2021-08-25 191607](https://user-images.githubusercontent.com/82143371/130827550-6b579029-5bc2-4859-acb8-7f8f72151994.png)

**User story and test case links**
"User story #692

**Comment by KostiantynStarynets** [comment]
Reproducing the test is possible only at https://speak-ukrainian.org.ua/
 The expected result matches the actual result.
 
 
![Знімок екрана 2023-01-09 224710](https://user-images.githubusercontent.com/117648097/211405864-d29db218-21ff-4129-b67e-6f656df28aac.jpg)
