### ISSUE TITLE
Список гуртків

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#76]
Як користувач я хочу мати змогу переглянути список гуртків.
Як керівник гуртка я хочу переглянути список зареєстрованих мною гуртків та центрів
Як користувач я хочу мати змогу при вході  на сайт обрати місто, як  мене цікавить 

PLACEHOLDER. Description TBD

frame 483, 560

**Comment by softservedata** [comment]
1. Backend is done
2. Frontend in progress
