### ISSUE TITLE
[Mobile. Home page] wrong alignment of elements in header after rotating the screen to landscape mode.

### ISSUE THREAD

**Issue by MartaHorbatska** [ita-social-projects/TeachUA#765]
Environment: Windows 10, Версия 92.0.4515.107 (Официальная сборка), (64 бит): mobile version.

- Iphone X

Mobile version: 

- Iphone XR (828 x 1792)  - Chrome (92.0.4515.90)
- Xiaomi redmi note 9 pro (1080*2400)

Reproducible: always
Build found: last commit

**Preconditions**
Go to https://speak-ukrainian.org.ua/dev/
Open mobile version of site. 

Steps to reproduce
Rotate the screen to landscape mode.
 
Actual result 
wrong alignment of elements in header after rotating the device.
- Iphone X
![image](https://user-images.githubusercontent.com/87965983/130943223-b5f975f9-b13f-40b2-aeea-7637dd36e1d4.png)

- Iphone XR (828 x 1792)  
![image](https://user-images.githubusercontent.com/87965983/130942255-4c717b06-1800-418f-8b7e-e431398fa6ee.png)

- Xiaomi redmi note 9 pro (1080*2400)
![image](https://user-images.githubusercontent.com/87965983/130942186-e3858470-4507-4583-aa90-edabd2f54911.png)

- Iphone 6/7/8

![image](https://user-images.githubusercontent.com/87965983/130944180-aba5b938-e3f8-4d5f-8ff8-138901ef3733.png)

Expected result
 alignment of elements in landscape orientation in proper positions.

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
