### ISSUE TITLE
[Mobile version.Розширений пошук] Switching between pages is not work when two categories are selected

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#769]
Environment: Windows 10, Google Chrome 92.0.4515.107 (Розробка) (64-розрядна версія)
Reproducible: always
Build found: the last commit

Preconditions:
The user should be logged in to the site https://speak-ukrainian.org.ua/dev/

Steps to reproduce
1.Go to 'Розширений пошук' button
2.Click on 'Розширений пошук' button
3.On the left side of the page find the parameters for advanced search
4. From "Категорія" check box select "Студії раннього розвитку" and "Танці, хореографія"
5. Click "Застосувати" button
6. Scroll down up to the bottom of the page and click on the second page.

Actual result
The second page is not opened( Switching between pages is not work when two categories are selected)

https://user-images.githubusercontent.com/82143371/131114667-11e98b93-cedf-4a3e-a415-2b24845e226a.mp4

**Expected result**
The second page is opened

User story # 274

**Comment by softservedata** [comment]
Duplicate issue #743
