### ISSUE TITLE
Звичайний пошук

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#77]
As a user, I want to find a club using basic search.

**Description:**

**‘Який гурток шукаєте?’ search** field is present on **‘Гуртки’, ‘Новини’** pages and **the main** page.

A user can find a club by entering the following parameters:

- **A name of a club**
- **A name of a category**
- **A name of a center**

If **a name of a category** is entered, the result of the search contains **all clubs which refer to this category**.
If **a name of a center** is entered, the result of the search contains **all clubs which refer to this center**.

Clubs are searched **within the selected city.**
The list of intermediate results is displayed in the drop-down and updated with each new character.

_E.g.:
If a user enters ‘спор’ in the search field, then an intermediate result contains ‘Спорт’ category (marked with an icon of the corresponding category) and all clubs whose names contain ‘спор’._

When a user clicks on an intermediate result, then a chosen club, category, or center is searched.

If the **‘Enter’ button** is pressed, the search is done **for matching characters in the title** (as in the example with "спор")
If the search is done from ‘Новини’ page or from the main page, the result of the search will be shown on ‘Гуртки’ page.

**AC:**
-A user can find a club using a basic search.
-A user can see the results of the search.
-A user can change a search query to another and see the updated results of the search.
-A user can delete a search query and see the initial state of the page.

![image](https://user-images.githubusercontent.com/78953350/111608248-ac1e7280-87e1-11eb-8cd1-8834ed76b0d0.png)

**Comment by softservedata** [comment]
1. Backend in progress
2. Frontend in progress

**Comment by MaryanaUstymenko** [comment]
Search option does not work

**Comment by DmytroKarman** [comment]
open BUG  https://github.com/ita-social-projects/TeachUA/issues/585

**Comment by Ytrygub** [comment]
User story has been updated according to the mentor's approve
