### ISSUE TITLE
Карта гуртків

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#78]
Як користувач я хочу переглянути на карті гуртки зі списку чи окремий гурток

AC:
При натисканні на конпку "показати на мапі" на карті позначені всі гуртки із списку, що зараз відображений (включаючи пагінацію)
Карта з"являється у вигляді pop-up з вертикальним списком гуртків зліва.
![Screenshot 2021-01-27 233855](https://user-images.githubusercontent.com/16098779/106057585-d95f7600-60f8-11eb-86ef-969f31da6aff.png)

! При відображенні списку центрів https://github.com/ita-social-projects/TeachUA/issues/77  конпка "показати на мапі" неактивна

**Comment by softservedata** [comment]
1. Backend is done
2. Frontend in progress
