### ISSUE TITLE
[Mobile version.'Розширений пошук'] Wrong font and alignment of the 'Застосувати' caption

### ISSUE THREAD

**Issue by muhalenuch** [ita-social-projects/TeachUA#785]
**Environment:** Iphone 7+ (1080 x 1920), IOS 14.7.1, browser Safari
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Розширений пошук'
3. Scroll down to 'Застосувати' button.

**Actual result**

1. 'Застосувати' caption is shifted to the right side of the screen.
2. Font and alignment of the 'Застосувати' caption differ from 'Очистити'.

![Incorrect alignment](https://user-images.githubusercontent.com/89358741/131911750-6cac07ee-2799-40aa-b9b8-29a7604c573b.png)
![Incorrect color,alignment,font](https://user-images.githubusercontent.com/89358741/131911762-6b8c4417-be33-4981-bcde-9955a41153e4.png)

**Expected result**

All captions have the same font, color, and alignment.

E.g.: "User story #

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
