### ISSUE TITLE
[Редагування профілю] Photo size validation does not work

### ISSUE THREAD

**Issue by NataliiaDovha** [ita-social-projects/TeachUA#788]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit 

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in

**Steps to reproduce**
1. Go to 'Мій Профіль' page
2. Click on 'Редагувати профіль'
3. Click on 'Завантажити фото' link
4. Select photo with 1) wrong resolution ( 100x200 pixels 
![image 100x200](https://user-images.githubusercontent.com/87872581/132177902-44d44af5-791b-49dd-ae48-5a7701faa2b2.jpg)
), 2) wrong size ( 7.4 MB 
![image 7MB](https://user-images.githubusercontent.com/87872581/132177989-28022760-7941-4cd6-8768-d659258b2245.jpg)
)
5. Click on 'Зберегти зміни'

**Actual result**
'Зберегти зміни' button is enabled. Photo is saved in the profile.
1)
![100x200](https://user-images.githubusercontent.com/87872581/132178555-da52e8a7-d470-4d85-8231-bf5d6d940235.png)
2) 
![7mb](https://user-images.githubusercontent.com/87872581/132178584-55e05754-1d83-4135-bf7f-1e6e58c5302b.png)

**Expected result**
'Зберегти зміни' button is disabled and 
![photo](https://user-images.githubusercontent.com/87872581/132180000-4f7c4599-068c-4b85-a1dc-fb1423854241.png)

**Postconditions**
Return edited data to the initial state

**User story link**
User story #164

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
