### ISSUE TITLE
[API] Fields validation doesn't work on back-end, for creating clubs via Postman

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#797]
Environment: Postman
Reproducible:** always
Build found:** last commit

Preconditions

1. Open DevTools in the browser
2. Log in https://speak-ukrainian.org.ua/dev/
3. Click on the Application tab in DevTools
4. Copy Access Token from Local Storage
5. Run Postman -> Create a new request

Steps to reproduce
1. Select the method POST in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/club
3. Click on the 'Authorization' tab and choose the Type "Bearer Token"
4. Paste copied generated in pre-conditions token in field 'Token'
5. Click on the Body tab and select Raw-> JSON format
6. Enter in Body field data

{
    "categoriesName": [
    
    ],
    "name": "",
    "ageFrom": 5,
    "ageTo": 18,
    "description": "{\"blocks\":[{\"key\":\"brl63\",\"text\":\" \",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
    "userId": "42",
    "locations": [
        {
            "name": "Локації",
            "cityName": "Київ",
            "districtName": "Святошинський",
            "stationName": "Арсенальна",
            "address": "вул Арсенальна",
            "coordinates": "50.456243, 30.375749",
            "phone": "",
            "key": 0.16199369629273064
        }
    ],
    "contacts": "{\"1\"::\"\"}"
}

Actual result
Status: 200. Club without "Назва", "Категорія", "Контакти" and "Опис" is created.
![GUI](https://user-images.githubusercontent.com/82143371/132679501-9469d719-624b-4ddf-a1c9-05f94f10b477.png)
![Postman Status 200](https://user-images.githubusercontent.com/82143371/132679676-14cf46d6-7ee6-45e1-b453-b160563b0566.png)

Expected result
Status: 400. Club without "Назва", "Категорія", "Контакти" and "Опис" isn't created.

"User story #70 

 "API" (for back-end bugs).

**Comment by NataliiaDovha** [comment]
It is possible to create a club without ‘Телефон *’ field which is mandatory. Also, 'Опис *' field is mandatory and text can not be empty, it is Min: 40 characters, Max: 1500 characters.
![Postman  create club](https://user-images.githubusercontent.com/87872581/135826407-6f693bfa-8b97-4435-91e6-670d8513652c.png)

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
