### ISSUE TITLE
[API] When user changes the password via Postman, the back-end doesn't require entering the existing password

### ISSUE THREAD

**Issue by yuliiahorak** [ita-social-projects/TeachUA#805]
Environment: Postman
Reproducible:** always
Build found:** last commit

Preconditions

1. Open DevTools in the browser
2. Log in https://speak-ukrainian.org.ua/dev/
3. Click on the Application tab in DevTools
4. Copy Access Token from Local Storage
5. Run Postman -> Create a new request

Steps to reproduce
1. Select the method PUT in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/user/{IDuser}
3. Click on the 'Authorization' tab and choose the Type "Bearer Token"
4. Paste copied generated in pre-conditions token in field 'Token'
5. Click on the Body tab and select Raw-> JSON format
6. Enter in Body field data
 {
    "firstName": "{Name}",
    "lastName": "{LastName}",
    "email": "{email}",
    "phone": "",
    "password": "{new password}",
    "roleName": "{role}",
    "urlLogo": "/upload/user/logo/{IDuser}/smoke-testing.jpg",
    "status": true

Actual result
When the user changes the password via Postman, the back-end doesn't require entering the existing password

Expected result
When the user changes the password via Postman, the back-end required entering the existing password

User story and test case links
"User story #164

**Comment by RomanKlymus** [comment]
The endpoint for changing the password has been changed to PATCH method on /api/user/{id}
