### ISSUE TITLE
[Редагування профілю] Phone number mask is not correct

### ISSUE THREAD

**Issue by ioleh-bleep-bloop** [ita-social-projects/TeachUA#812]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.159 (64-bit)
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in 
3. Click on 'Мій Профіль'
4. Click on 'Редагувати профіль'
5. Delete entered number

**Actual result**
Mask is +380
![Phone_mask_editprofile](https://user-images.githubusercontent.com/52464559/133581104-2ca2c5cd-3fa7-4628-b836-1254b5aec71c.jpg)

**Expected result**

‘Телефон’ | Format: input mask '+38(___) ___ __ __'

**User story and test case links**
E.g.: "User story #164

**Comment by AnastasiiaKukh** [comment]
Bug is not fixed
