### ISSUE TITLE
[Реєстрація] Phone number mask is not correct

### ISSUE THREAD

**Issue by ioleh-bleep-bloop** [ita-social-projects/TeachUA#825]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.159 (64-bit)
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on the profile drop-down list
3. Click on the 'Зареєструватися'

**Actual result**
Mask is +380_________
![Phone_mask_reg](https://user-images.githubusercontent.com/52464559/134054084-3f62aa41-4d6e-4801-a7a5-56777e630446.jpg)

**Expected result**
‘Телефон’ | Format: input mask '+38(___) ___ __ __'

**User story and test case links**
E.g.: "User story #97

**Comment by AnastasiiaKukh** [comment]
Bug is not fixed

**Comment by AnastasiiaKukh** [comment]
Bug is not fixed
