### ISSUE TITLE
[Footer] Unnecessary line break in the inscription 

### ISSUE THREAD

**Issue by NataliiaDovha** [ita-social-projects/TeachUA#833]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** last commit

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/

**Steps to reproduce**
1. Scroll down to the footer

**Actual result**
There is a line break in the '©2021 Design by Qubstudio & Development by SoftServe' inscription 
![incorrect footer](https://user-images.githubusercontent.com/87872581/134963989-7554ee3b-95d0-498b-bca4-fd309e74dc75.png)

**Expected result**
There is no line break in the '©2021 Design by Qubstudio & Development by SoftServe' inscription 
![correct footer](https://user-images.githubusercontent.com/87872581/134964010-620437cb-765e-4d7c-bff8-cef970d90d47.png)

**User story and test case links**
User story

**Comment by AnastasiiaKukh** [comment]
Bug  fixed and close
