### ISSUE TITLE
[Гурток. Додати коментар] Infinite requests in Network when user try to add comment

### ISSUE THREAD

**Issue by ioleh-bleep-bloop** [ita-social-projects/TeachUA#840]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.159 (64-bit)
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Search any club
3. Click on 'Детальніше'
4. Click on 'Залишити коментар'
5. Press F12 and click on the Network tab

**Actual result**
Infinite user requests
![user requests](https://user-images.githubusercontent.com/52464559/135415805-a589e23d-307d-4465-8f3d-3edf258b95ce.jpg)

**Expected result**
Requests aren't infinite

**User story and test case links**
E.g.: "User story #

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
