### ISSUE TITLE
[Реєстрація.API] Any user is able to create Admin_role profile 

### ISSUE THREAD

**Issue by ioleh-bleep-bloop** [ita-social-projects/TeachUA#842]
**Environment:** Postman v9.0.3
**Reproducible:** always
**Build found:** last commit

**Steps to reproduce**

1. Select the method POST in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/signup
3. Click on the Body tab and select Raw-> JSON format
4. Enter in Body field data:
{
  "firstName": "User",
  "lastName": "New",
  "email": "osyxcf@mailto.plus",
  "password": "qweqweqwe",
  "phone": "000000000000000000",
  "roleName": "ROLE_ADMIN"
}

**Actual result**
User is created as admin
![user admin](https://user-images.githubusercontent.com/52464559/135580887-dca15750-86cf-4103-941f-d1dd4045bc18.jpg)

**Expected result**
User doesn't have permission to register as admin 

**User story and test case links**
E.g.: "User story #97

**Comment by AnastasiiaKukh** [comment]
Bug is close
