### ISSUE TITLE
[Гуртки] Incorrect part of a page opens when clicking on 'Детальніше' link

### ISSUE THREAD

**Issue by muhalenuch** [ita-social-projects/TeachUA#848]
**Environment:** Windows 10 19043.928, browser (Chrome) 92.0.4515.159 (64)
**Reproducible:** always
**Build found:** last commit 

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Гуртки' tab
3. Click on any 'Детальніше' button
4. Scroll down to 'Детальніше' link and click on it

**Actual result**
The bottom of the page is opened

https://user-images.githubusercontent.com/89358741/135652879-0aca4168-4e46-4377-83ff-50a6707a4fbd.mp4

**Expected result**
The top of the page is opened

E.g.: "User story

**Comment by AnastasiiaKukh** [comment]
Bug is close
