### ISSUE TITLE
[API] Validation of userId doesn't work on back-end, for creating clubs via Postman

### ISSUE THREAD

**Issue by NataliiaDovha** [ita-social-projects/TeachUA#856]
**Environment:** Windows 10, Google Chrome Version 92.0.4515.107 (Official Build) (64-bit), Postman
**Reproducible:** always
**Build found:** last commit

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Log in with an already registered user
3. Copy your Access Token from Local Storage
4. Run Postman
5. On the 'Authorization' tab choose the Type "Bearer Token" and paste your Access Token
6. Check what is your userId

**Steps to reproduce**
1. Select the method POST in Postman
2. Fill in URL field https://speak-ukrainian.org.ua/dev/api/club
3. Click on the Body tab and select Raw-> JSON format
4. Enter in Body field data
```
{
"categoriesName": [ "Спортивні секції"

],
"name": "Club",
"ageFrom": 5,
"ageTo": 18,
"description": "{\"blocks\":[{\"key\":\"brl63\",\"text\":\" tzwwwwwwwwwwwwwwwwwwwwwtttttttttttttttttttttttttt\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
"userId": "42",
"locations": [
    {
        "name": "Локації",
        "cityName": "Київ",
        "districtName": "Святошинський",
        "stationName": "Арсенальна",
        "address": "вул Арсенальна",
        "coordinates": "50.456243, 30.375749",
        "phone": "852741963",
        "key": 0.16199369629273064
    }
],
"contacts": "{\"1\"::\"\"}"
}
```
5. Make sure you use userId of another person

**Actual result**
The club is created. Status 200 OK. User can create a club for another user by using his userId.
![Postman create club for another user](https://user-images.githubusercontent.com/87872581/135829550-00cfc33f-9eaa-4dc7-810e-aab41491c5a2.png)

**Expected result**
The club is not created. User can not create a club for another user by using his userId.

**User story and test case links**
User story #70

**Comment by TarasHaiduk** [comment]
{
"categoriesName": [ "Спортивні секції"

],
"name": "Clubing",
"ageFrom": 5,
"ageTo": 18,
"description": "{\"blocks\":[{\"key\":\"brl63\",\"text\":\" tzwwwwwwwwwwwwwwwwwwwwwtttttttttttttttttttttttttt\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
"userId": "42",
"locations": [
    {
        "name": "Локації",
        "cityName": "Київ",
        "districtName": "Святошинський",
        "stationName": "Арсенальна",
        "address": "вул Арсенальна",
        "coordinates": "50.456243, 30.375749",
        "phone": "0933225937",
        "key": 0.16199369629273064
    }
],
"contacts": "{\"1\"::\"\"}"
}

**Comment by VitaliiPopovych1408** [comment]
{
"categoriesName": [ "Спортивні секції"

],
"name": "Clubs",
"ageFrom": 5,
"ageTo": 18,
"description": "{\"blocks\":[{\"key\":\"brl63\",\"text\":\" tzwwwwwwwwwwwwwwwwwwwwwtttttttttttttttttttttttttt\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
"userId": "49",
"locations": [
    {
        "name": "Локації",
        "cityName": "Київ",
        "districtName": "Святошинський",
        "stationName": "Арсенальна",
        "address": "вул Арсенальна",
        "coordinates": "50.456243, 30.375749",
        "phone": "0937611308",
        "key": 0.16199369629273064
    }
],
"contacts": "{\"1\"::\"\"}"
}
![image](https://user-images.githubusercontent.com/42620939/159656679-d3267ccf-563d-4add-bb53-b5c05a419290.png)
