### ISSUE TITLE
[Реєстрація користувача] 'FirstName' and 'LastName' fields accept the Russian alphabet

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#861]
**Environment:** Windows 10, Google Chrome version 92.0.4515.107
**Reproducible:** always
**Build found:** last commit 

**Steps to reproduce**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Click on 'Зареєструватися' button
3. Enter Ё Ъ Ы Э in the 'FirstName and 'LastName' fields

**Actual result**
'FirstName' and 'LastName' fields accept the Russian alphabet 
![image](https://user-images.githubusercontent.com/87894920/135981749-7d832656-58ea-43a6-8a13-b1cb55fd36e9.png)

**Expected result**
'FirstName' and 'LastName' fields do not accept the letters of Russian alphabet

**User story and test case links**
User story #167

**Comment by softservedata** [comment]
Update Regex on frontend and backend
