### ISSUE TITLE
[Додати гурток] The 'Опис' field on the 'Опис' tab accepts the letters of the Russian alphabet 

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#871]
**Environment:** Windows 10, Google Chrome version 92.0.4515.107
**Reproducible:** always
**Build found:** last commit 

**Steps to reproduce**
1. Log in https://speak-ukrainian.org.ua/dev/
2. Click on ' Додати гурток' on a home page or in a private office
3. Fill in the 'Основна інформація' and 'Контакти' tabs
4. Fill in the 'Опис' field on the 'Опис' tab with the letters of the Russian alphabet ЪЫЭ

**Actual result**
The 'Опис' field accepts the letters of the Russian alphabet 
![image](https://user-images.githubusercontent.com/87894920/136329099-2ce21094-3775-4159-8d29-4c3c74d138ff.png)

**Expected result**
The 'Опис' field does not accept the letters of the Russian alphabet 

**User story and test case links**
"User story #70

**Comment by AnastasiiaKukh** [comment]
Bug is fixed
