### ISSUE TITLE
[Додати центр] The 'Опис' field on the 'Опис' tab accepts the letters of the Russian alphabet

### ISSUE THREAD

**Issue by IuliiaKrivenkova** [ita-social-projects/TeachUA#872]
**Environment:** Windows 10, Google Chrome version 92.0.4515.107
**Reproducible:** always
**Build found:** last commit 

**Steps to reproduce**
1. Log in https://speak-ukrainian.org.ua/dev/
2. Click on the profile drop-down list
3. Click on 'Додати центр'
4. Fill all mandatory fields on 'Основна інформація' tab
5. Fill all mandatory fields on 'Контакти' tab
6. Fill in the 'Опис' field on the 'Опис' tab with the letters of the Russian alphabet ЪЫЭ

**Actual result**
The 'Опис' field on the 'Опис' tab accepts the letters of the Russian alphabet
![image](https://user-images.githubusercontent.com/87894920/136331509-c42d33cd-ebae-4681-bcea-75f173a14480.png)

**Expected result**
The 'Опис' field on the 'Опис' tab does not accept the letters of the Russian alphabet

**User story and test case links**
"User story #71

**Comment by AnastasiiaKukh** [comment]
Bug is close
