### ISSUE TITLE
[Registration] Input fields on ‘Registration’ pop-up is coming out of borders of pop-up on Tablet devices

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#900]
**Environment:** Windows 10, Google Chrome Version 94.0.4606.81 (Official Build) (64-bit)
**Reproducible:** always.
**Build found:** last commit.

**Preconditions**
1. Go to https://speak-ukrainian.org.ua/dev/
2. Make sure you are unauthorised user
3. Click F12 - Toggle device toolbar
4. In 'Dimensions' drop-down select 'Responsive'
5. Set 'Width' field with '824' px

**Steps to reproduce**
1. Click on profile picture in top-right corner of the page
2. Select 'Зареєструватися'

**Actual result**
Input fields on ‘Registration’ pop-up is coming out of borders of pop-up on ≤824 px width.

**Expected result**
Input fields on ‘Registration’ pop-up should fit in borders of pop-up on any dimensions of screen.

<details>
  <summary>Screenshot:</summary>

![Screenshot_15](https://user-images.githubusercontent.com/79206807/137486863-32117006-357b-4b92-9ab4-9852caf2cefe.png)
</details>

**Comment by AnastasiiaKukh** [comment]
Bug fixed and close

**Comment by AnastasiiaKukh** [comment]
Bug fixed and closed
