### ISSUE TITLE
[API. Log In] Incorrect responce status is appeared when user with unconfirmed email address tries to log in

### ISSUE THREAD

**Issue by Wollene** [ita-social-projects/TeachUA#901]
**Environment:** Windows 10 x64, Postman v9.0.7.
**Reproducible:** always.
**Build found:** last commit.

**Preconditions**
1. Run Postman
2. Create new request > Choose 'POST' in 'Method' drop-down
3. Enter request URL: https://speak-ukrainian.org.ua/dev/api/signin

**Steps to reproduce**
1. Choose Body > raw > JSON
2. Enter a request for authorization of the user with unconfirmed email address (e.g. "email":"ddd222@t.me",
"password":"11111111")
3. Click on 'Send' button

**Actual result**
Server response appears with 500 status - 'Internal Server Error'.

**Expected result**
Server response should appear with 403 status - 'Forbidden'.

<details>
  <summary>Screenshot:</summary>

![Screenshot_24](https://user-images.githubusercontent.com/79206807/137489268-26fac612-617d-4fd9-b6a1-537858431994.png)
</details>

**Comment by AnastasiiaKukh** [comment]
Bug is fixed and closed
