### ISSUE TITLE
Реєстрація користувача

### ISSUE THREAD

**Issue by kushmih** [ita-social-projects/TeachUA#97]
As “Керівник” I want to get registered on the site to view content, leave comments, add clubs and change personal data. 
As “Відвідувач” I want to get registered on the site to view content, leave comments and change personal data.

General Description:
Sign up on the site navigates to the “Реєстрація” page with the empty fields to create a new user.
The “Реєстрація” page allows visitors to create a new user with the “Відвідувач” or the “Керівник” role. 

About roles:
The “Відвідувач” role allows:
view content
leave comments
change personal data 
The “Керівник” roles allows:
view content
leave comments
add clubs
change personal data (except changing a role after adding clubs) 
 Both the “Відвідувач” and the “Керівник” tabs consist of:

Text boxes: 
‘* Прізвище’,
‘* Ім’я’,
‘* Телефон’, 
‘* Email’
‘* Пароль’
‘* Підтвердити пароль’ 

‘Зареєструватися’ button
‘X’ icon
‘Натискаючи кнопку ‘Зареєструватися’, я даю згоду на обробку персональних даних’ text.
Default states of all controls look like as in the mockup (mockup is attached).
These text boxes are mandatory and have the following format:
•‘* Прізвище’, ‘* Ім'я’: up to 25 characters, case sensitive. Can contain (but cannot start and end with the following reserved characters: space, apostrophe and hyphen). Can’t contain numbers and reserved characters ( ~, , !, @, #, $, %, ^, &, *, (, ), _, =, +, {, }, [, ], /, |, \, :, ; ," , <, >, ?,). •‘* Телефон’. Can contain only 13 characters. Starts only with “+380”. Can’t contain letters and reserved characters ( ~, , !, @, #, $, %, ^, &, , (, ), _, =, +, {, }, [, ], /, |, , :, ; ," , <, >, ?,).
•‘ Email’: according to the following format: local-part@domain.com
•‘* Пароль’: Cannot be shorter than 8 characters and longer than 20 characters.Can contain the following characters: upper/lower-case letters, numbers and reserved characters ( ~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, , :, ; ," , <, >, ?,). Symbols entered in ‘Пароль’ field are transformed in asterisks on typing. 
• ‘ Підтвердити пароль’: ‘* Підтвердити пароль’ should be the same as entered data in ‘* Пароль’ text box. Symbols entered in ‘*Підтвердити пароль’ field are transformed in asterisks on typing.

Users will get error messages under the corresponding fields in red colour.
On entering invalid data the error message is shown under the corresponding field and the entered data remains in the field.

If entered data is invalid in: | Reason | Error messages
-- | -- | --
‘* Прізвище’, ‘* Ім'я’ text boxes | enter more than 25 characters | ‘Прізвище не може містити більше, ніж 25 символів’/ ‘Ім'я не може містити більше, ніж 25 символів’
‘* Прізвище’, ‘* Ім'я’ text boxes | enter reserved characters (except  space, apostrophe and hyphen characters) | ‘Прізвище не може містити спеціальні символи’/‘Ім’я не може містити спеціальні символи’
‘* Прізвище’, ‘* Ім'я’ text boxes | enter number characters | ‘Прізвище не може містити цифри’/‘Ім’я не може містити цифри’
‘* Прізвище’, ‘* Ім'я’ text boxes | start or end with space, apostrophe or hyphen characters | ‘Прізвище повинно починатися та закінчуватися літерою’ /‘Ім’я повинно починатися та закінчуватися літерою’
‘* Прізвище’, ‘* Ім'я’, ‘Телефон’, ‘ Email’, ‘Пароль’, ‘ Підтвердити пароль’  text boxes | user doesn’t enter any data in the corresponding field | after clicking ‘Зареєструватися’ button the ‘* Прізвище’, ‘* Ім’я’, ‘* Телефон’,  ‘* Email’, ‘Пароль’, ‘ Підтвердити пароль’  text boxes are bordered in red colour  and  the next messages appear in the respective placeholders : ‘Введіть прізвище’,‘Введіть ім’я’, ‘+38(___) ___ __ __’, ‘Введіть email’, ‘Введіть  пароль’,  ‘Підтвердіть пароль’
‘* Телефон’ text box | enter reserved characters | ‘Телефон не може містити спеціальні символи’
‘* Телефон’ text box | enter letters | ‘Телефон не може містити літери’
‘* Телефон’ text box | enter less than 10 symbols | ‘Телефон не відповідає вказаному формату’
‘* Email’ text box | _ | ‘Некоректний формат email’
‘* Пароль’ text box | enter less than 8 or more than 20 characters | ‘Пароль не може бути коротшим,  ніж 8 та довшим, ніж 20 символів’
‘* Підтвердити пароль’ text box | entered data in ‘*Підтвердити пароль’ field isn’t the same as entered data in ‘*Пароль’ field | “Значення поля ‘Підтвердити пароль’ має бути еквівалентним значенню поля ‘Пароль’”

‘Зареєструватися’ button accepts entered data, if valid, and a pop-up with “Ми відправили лист-підтвердження на вказаний Вами е-mail. Будь ласка, перейдіть за посиланням в отриманному листі для завершення реєстрації” message is shown.
After a user clicks on the link in the registered email a new tab is opened and the “Реєстрація успішно завершена” message is shown.
‘X’ icon doesn’t store any entered data to the database and returns a user to the main page.

**Acceptance criteria:**
'Зареєструватися' element is present.
'Реєстрація' page is displayed after clicking the “Зареєструватися” menu item and matches the mock-up.
A message about confirming the registration is shown in the pop up after clicking the “Зареєструватися” button and filling all mandatory fields with valid data. 
The user receives such a message on email in the following format: 
'Шановний/а "Прізвище" "Ім'я"!
Для підтвердження Вашої реєстрації, будь ласка, перейдіть за посиланням нижче: Підтвердити реєстрацію Дякуємо! Ініціатива "Навчай українською" '.
New user with valid data is created (saved to database) according to existing rules.
Last entered data on the ‘Реєстрація’ page are remembered in case a user closes the page and returns back later.
Upon entering invalid data in any field or leave any mandatory field empty the "Зареєструватися" button becomes disabled.

<img width="410" alt="Screenshot 2021-04-08 at 22 29 14" src="https://user-images.githubusercontent.com/78917969/114085317-e0a1bd80-98b9-11eb-8c9b-31d3afd6c8ba.png">

**Comment by MartaFisher** [comment]
[Реєстрація користувача] The password input field allows: №, /, є

**Comment by NataliiaDovha** [comment]
Update:

1. ‘Пароль’ сan contain the following LATIN characters: upper/lower-case, numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?) // RUS, UKR letters are not valid
Error message appears: “Пароль повинен містити великі/маленькі літери латинського алфавіту, цифри та спеціальні символи”
2. ‘Телефон’ field has the following format and mask: "+38(___) ___ __ __".
3. Error message "Телефон не відповідає формату +38(___) ___ __ __" appears on entering 1) less than 13 symbols, 2) more than 13 symbols, 3) reserved characters, and 4) letters in the ‘Телефон’ field.

**Comment by AnastasiiaKukh** [comment]
Update:

‘Пароль’ must contain the following LATIN characters: upper/lower-case, numbers and reserved characters (~, `, !, @, #, $, %, ^, &, (, ), _, =, +, {, }, [, ], /, |, :, ;,", <, >, ?) // RUS, UKR letters are not valid.

Error message appears: “Пароль повинен містити великі/маленькі літери латинського алфавіту, цифри та спеціальні символи”
